const fs = require('fs');
const path = require('path');

const data = [
    ["与える", "to give, to provide", "子供たちに平等な教育の機会を与えるべきだ。", "We should provide children with equal educational opportunities.", ["vocabulary", "verb", "transitive"]],
    ["扱う", "to handle, to deal with", "この機械は精密なので、慎重に扱ってください。", "This machine is delicate, so please handle it with care.", ["vocabulary", "verb", "transitive"]],
    ["余る", "to remain, to be left over", "予算が少し余ったので、新しいソフトウェアを導入した。", "Since we had a little budget left over, we introduced some new software.", ["vocabulary", "verb", "intransitive"]],
    ["編む", "to knit, to compile", "祖母は冬に向けてセーターを編んでくれている。", "My grandmother is knitting a sweater for the winter.", ["vocabulary", "verb", "transitive"]],
    ["争う", "to dispute, to compete", "二つの企業が市場シェアを巡って激しく争っている。", "The two companies are competing fiercely over market share.", ["vocabulary", "verb", "intransitive"]],
    ["改める", "to change, to revise, to correct", "来月から社内の評価制度を改める方針だ。", "We plan to revise the company's evaluation system starting next month.", ["vocabulary", "verb", "transitive"]],
    ["表す", "to express, to represent", "彼の表情は現在の複雑な心境を表していた。", "His expression represented his current complex state of mind.", ["vocabulary", "verb", "transitive"]],
    ["現す", "to show, to reveal", "ようやく太陽が雲の間から姿を現した。", "The sun finally revealed itself from between the clouds.", ["vocabulary", "verb", "transitive"]],
    ["著す", "to write, to publish", "彼女は長年の研究成果を一冊の本に著した。", "She published the results of her years of research in a book.", ["vocabulary", "verb", "transitive"]],
    ["合わせる", "to match, to unite, to combine", "周囲のペースに合わせて作業を進めるのは意外と難しい。", "It's surprisingly difficult to proceed with the work while matching the pace of those around you.", ["vocabulary", "verb", "transitive"]],
    ["慌てる", "to panic, to rush", "急な仕様変更にも慌てることなく、チームは冷静に対応した。", "The team responded calmly to the sudden specification change without panicking.", ["vocabulary", "verb", "intransitive"]],
    ["言い出す", "to start talking, to propose", "会議の終盤になって、彼が突然新しいアイデアを言い出した。", "Toward the end of the meeting, he suddenly proposed a new idea.", ["vocabulary", "verb", "transitive"]],
    ["至る", "to reach, to lead to", "度重なる協議の末、ついに合意に至った。", "After repeated discussions, we finally reached an agreement.", ["vocabulary", "verb", "intransitive"]],
    ["抱く", "to harbor, to hold", "多くの市民が現在の経済状況に対して不安を抱いている。", "Many citizens harbor anxiety about the current economic situation.", ["vocabulary", "verb", "transitive"]],
    ["威張る", "to boast, to act arrogant", "彼は昇進したからといって威張るような人間ではない。", "He is not the kind of person to act arrogant just because he got promoted.", ["vocabulary", "verb", "intransitive"]],
    ["嫌がる", "to dislike, to hate (doing)", "子供が野菜を食べるのを嫌がって困っている。", "I'm having trouble because my child dislikes eating vegetables.", ["vocabulary", "verb", "transitive"]],
    ["伺う", "to ask, to visit (humble)", "来週の火曜日にそちらのオフィスへ伺ってもよろしいでしょうか。", "Would it be alright if I visited your office next Tuesday?", ["vocabulary", "verb", "transitive"]],
    ["浮かべる", "to float, to show (on one's face)", "彼女は昔のアルバムを見ながら、懐かしそうな笑みを浮かべた。", "She showed a nostalgic smile while looking at the old photo album.", ["vocabulary", "verb", "transitive"]],
    ["受け持つ", "to take charge of", "今学期から三年生の英語のクラスを受け持つことになった。", "Starting this semester, I will be taking charge of the third-year English class.", ["vocabulary", "verb", "transitive"]],
    ["動かす", "to move, to operate", "このプロジェクトを動かすには、さらに多くの資金が必要だ。", "We need more funds to get this project moving.", ["vocabulary", "verb", "transitive"]],
    ["失う", "to lose", "顧客からの信頼を一度失うと、回復するのは容易ではない。", "Once you lose the trust of your customers, it is not easy to recover.", ["vocabulary", "verb", "transitive"]],
    ["疑う", "to doubt, to suspect", "自分の目を疑うほど、信じられない光景が広がっていた。", "An unbelievable scene spread out before me, to the point where I doubted my own eyes.", ["vocabulary", "verb", "transitive"]],
    ["撃つ", "to shoot", "警官は警告のために空に向かって銃を撃った。", "The police officer shot his gun into the air as a warning.", ["vocabulary", "verb", "transitive"]],
    ["移す", "to move, to transfer", "本社を都心から郊外へ移す計画が進行中だ。", "A plan to move the headquarters from the city center to the suburbs is underway.", ["vocabulary", "verb", "transitive"]],
    ["訴える", "to appeal, to complain of", "一部の住民が建設工事の騒音被害を訴えている。", "Some residents are complaining about the noise damage from the construction work.", ["vocabulary", "verb", "transitive"]],
    ["奪う", "to snatch away, to steal", "その美しい景色は、一瞬にして観光客の心を奪った。", "That beautiful scenery instantly stole the hearts of the tourists.", ["vocabulary", "verb", "transitive"]],
    ["埋める", "to bury, to fill up", "今年の赤字をどうやって埋めるかが最大の課題だ。", "How to fill up this year's deficit is our biggest challenge.", ["vocabulary", "verb", "transitive"]],
    ["敬う", "to respect, to honor", "年長者を敬うという文化は、今でも大切にされている。", "The culture of respecting one's elders is still valued today.", ["vocabulary", "verb", "transitive"]],
    ["裏切る", "to betray", "消費者の期待を裏切るような製品は、すぐに市場から消えていく。", "Products that betray consumers' expectations quickly disappear from the market.", ["vocabulary", "verb", "transitive"]],
    ["占う", "to forecast, to tell fortunes", "来年の経済動向を占う上で、この指標は非常に重要だ。", "This indicator is very important in forecasting next year's economic trends.", ["vocabulary", "verb", "transitive"]],
    ["恨む", "to resent, to hold a grudge", "失敗は自分の責任であり、他人を恨むのは筋違いだ。", "The failure is my own responsibility, and holding a grudge against others is unreasonable.", ["vocabulary", "verb", "transitive"]],
    ["羨む", "to envy", "他人の成功を羨む前に、自分自身の努力を見直すべきだ。", "Before envying the success of others, you should review your own efforts.", ["vocabulary", "verb", "transitive"]],
    ["売り切れる", "to be sold out", "人気アーティストのコンサートチケットは、発売開始から数分で売り切れた。", "The popular artist's concert tickets sold out within minutes of going on sale.", ["vocabulary", "verb", "intransitive"]],
    ["追いかける", "to chase, to run after", "警察は逃走した犯人の車をパトカーで追いかけた。", "The police chased the fleeing suspect's car in a patrol car.", ["vocabulary", "verb", "transitive"]],
    ["追い越す", "to pass, to overtake", "高速道路でトラックを追い越す際は、周囲の状況に十分注意してください。", "When overtaking a truck on the highway, please pay close attention to your surroundings.", ["vocabulary", "verb", "transitive"]],
    ["追い付く", "to catch up", "競合他社の技術力に追い付くため、研究開発への投資を増やす。", "We will increase investment in research and development to catch up with our competitors' technological capabilities.", ["vocabulary", "verb", "intransitive"]],
    ["応じる", "to respond, to accept", "お客様の多様なニーズに応じるため、新サービスを立ち上げた。", "We launched a new service to respond to the diverse needs of our customers.", ["vocabulary", "verb", "intransitive"]],
    ["終える", "to finish, to complete", "すべての検査を終えるまで、あと一週間ほどかかります。", "It will take about another week until we finish all the inspections.", ["vocabulary", "verb", "transitive"]],
    ["覆う", "to cover, to hide", "山頂は厚い雲に覆われており、景色を全く楽しめなかった。", "The summit was covered in thick clouds, and we couldn't enjoy the view at all.", ["vocabulary", "verb", "transitive"]],
    ["補う", "to compensate for, to supplement", "労働力不足を補うために、AIやロボットの導入が進められている。", "The introduction of AI and robots is being promoted to compensate for the labor shortage.", ["vocabulary", "verb", "transitive"]],
    ["贈る", "to give (as a gift), to present", "長年会社に貢献してくれた彼に、感謝の記念品を贈った。", "We presented a commemorative gift of appreciation to him, who has contributed to the company for many years.", ["vocabulary", "verb", "transitive"]],
    ["怠る", "to neglect, to fail to do", "日々のメンテナンスを怠ると、深刻な機械トラブルにつながる。", "Neglecting daily maintenance leads to serious machine trouble.", ["vocabulary", "verb", "transitive"]],
    ["押さえる", "to hold down, to suppress", "イベントの企画書を作る前に、まずは要点を押さえておきましょう。", "Before creating the event proposal, let's nail down the main points first.", ["vocabulary", "verb", "transitive"]],
    ["収める", "to achieve, to obtain, to supply", "今回のプロジェクトで、私たちのチームは大きな成功を収めた。", "Our team achieved great success with this project.", ["vocabulary", "verb", "transitive"]],
    ["納める", "to pay (taxes), to deliver", "期限までにしっかりと税金を納めるのは国民の義務である。", "Paying taxes properly by the deadline is a citizen's duty.", ["vocabulary", "verb", "transitive"]],
    ["治める", "to govern, to manage", "新しい市長は、荒れていた市政を見事に治めた。", "The new mayor splendidly governed the chaotic municipal administration.", ["vocabulary", "verb", "transitive"]],
    ["恐れる", "to fear, to be afraid of", "失敗を恐れていては、新しいことに挑戦することはできない。", "If you fear failure, you won't be able to challenge yourself with new things.", ["vocabulary", "verb", "transitive"]],
    ["教わる", "to be taught, to learn from", "新人時代に先輩から教わった仕事の基本は、今でも役立っている。", "The basics of work I learned from my seniors during my rookie days are still useful today.", ["vocabulary", "verb", "transitive"]],
    ["落ち込む", "to feel down, to decline", "先月の売上が大幅に落ち込んでしまい、対策を急いでいる。", "Last month's sales declined significantly, and we are rushing to take countermeasures.", ["vocabulary", "verb", "intransitive"]],
    ["驚かす", "to surprise, to frighten", "彼の突然の引退発表は、世界中のファンを驚かせた。", "His sudden retirement announcement surprised fans all over the world.", ["vocabulary", "verb", "transitive"]],
    ["溺れる", "to drown, to indulge in", "海で溺れかけていた子供が、偶然通りかかった人に救助された。", "A child who was almost drowning in the sea was rescued by a passerby.", ["vocabulary", "verb", "intransitive"]],
    ["思い込む", "to be under the impression, to assume", "ずっと自分の責任だと思い込んでいたが、実はシステムのエラーだった。", "I had assumed all along that it was my fault, but it was actually a system error.", ["vocabulary", "verb", "intransitive"]],
    ["思いつく", "to think of, to hit upon", "散歩をしている途中で、新しいビジネスのアイデアを思いついた。", "I hit upon a new business idea while I was taking a walk.", ["vocabulary", "verb", "transitive"]],
    ["及ぼす", "to exert, to cause, to affect", "この法律の改正は、業界全体に大きな影響を及ぼすだろう。", "This revision of the law will likely have a major impact on the entire industry.", ["vocabulary", "verb", "transitive"]],
    ["折る", "to fold, to break", "強風で庭の木の枝が折れてしまった。", "The branches of the tree in the garden were broken by the strong wind.", ["vocabulary", "verb", "transitive"]],
    ["降ろす", "to drop off, to take down", "駅の南口で客を降ろした後、タクシーは走り去った。", "After dropping off the passenger at the south exit of the station, the taxi drove away.", ["vocabulary", "verb", "transitive"]],
    ["代える", "to replace, to substitute", "資源の枯渇を防ぐため、プラスチックを別の素材に代える動きが加速している。", "To prevent resource depletion, the movement to replace plastic with other materials is accelerating.", ["vocabulary", "verb", "transitive"]],
    ["抱える", "to hold, to have (problems)", "その企業は多額の負債を抱えており、経営再建が急務となっている。", "That company holds a large amount of debt, and corporate restructuring is an urgent task.", ["vocabulary", "verb", "transitive"]],
    ["限る", "to restrict, to limit", "この割引キャンペーンは、初めて当店をご利用のお客様に限ります。", "This discount campaign is limited to customers using our store for the first time.", ["vocabulary", "verb", "intransitive"]],
    ["隠れる", "to hide, to be hidden", "太陽が雲の陰に隠れ、急に辺りが暗くなった。", "The sun hid behind the clouds, and the surroundings suddenly grew dark.", ["vocabulary", "verb", "intransitive"]],
    ["嗅ぐ", "to sniff, to smell", "ガス漏れのような不審な臭いを嗅いだら、すぐに通報してください。", "If you smell a suspicious odor like a gas leak, please report it immediately.", ["vocabulary", "verb", "transitive"]],
    ["欠ける", "to lack, to be missing, to chip", "彼の提案は斬新だが、実現性に欠ける部分がある。", "His proposal is innovative, but there are parts where it lacks feasibility.", ["vocabulary", "verb", "intransitive"]],
    ["囲む", "to surround, to encircle", "大きなテーブルを家族全員で囲んで、夕食を楽しんだ。", "The whole family surrounded the large table and enjoyed dinner.", ["vocabulary", "verb", "transitive"]],
    ["重なる", "to overlap, to pile up", "不運なトラブルが重なり、納品が予定より遅れてしまった。", "Due to overlapping unfortunate troubles, the delivery was delayed beyond the schedule.", ["vocabulary", "verb", "intransitive"]],
    ["飾る", "to decorate", "オフィスのエントランスに、季節の花を飾ることにした。", "We decided to decorate the office entrance with seasonal flowers.", ["vocabulary", "verb", "transitive"]],
    ["偏る", "to be unbalanced, to lean", "情報収集が一部のメディアに偏ると、客観的な判断ができなくなる。", "If your information gathering leans toward certain media, you won't be able to make objective judgments.", ["vocabulary", "verb", "intransitive"]],
    ["語る", "to talk, to narrate", "社長は創業当時の苦労について、社員たちに熱く語った。", "The president talked passionately to the employees about the hardships when the company was founded.", ["vocabulary", "verb", "transitive"]],
    ["悲しむ", "to be sad, to mourn", "ペットの突然の死を、家族全員が深く悲しんでいる。", "The entire family is deeply mourning the sudden death of their pet.", ["vocabulary", "verb", "transitive"]],
    ["通う", "to commute, to go to and from", "語学力を維持するために、週に二回英会話スクールに通っている。", "To maintain my language skills, I commute to an English conversation school twice a week.", ["vocabulary", "verb", "intransitive"]],
    ["枯れる", "to wither, to dry up", "夏の厳しい暑さで、庭の植物がすっかり枯れてしまった。", "Due to the severe summer heat, the plants in the garden have completely withered.", ["vocabulary", "verb", "intransitive"]],
    ["かわいがる", "to love, to show affection to", "彼は新入社員をとてもかわいがり、熱心に仕事を教えている。", "He shows a lot of affection to the new employees and eagerly teaches them the job.", ["vocabulary", "verb", "transitive"]],
    ["乾かす", "to dry", "雨に濡れたコートを、ストーブの近くで乾かした。", "I dried my rain-soaked coat near the stove.", ["vocabulary", "verb", "transitive"]],
    ["代わる", "to take the place of, to replace", "体調不良の彼に代わって、私がプレゼンテーションを行います。", "I will give the presentation in place of him, who is feeling unwell.", ["vocabulary", "verb", "intransitive"]],
    ["気付く", "to notice, to realize", "書類を提出した後になって、重大な入力ミスに気付いた。", "I realized a major input error after I had already submitted the document.", ["vocabulary", "verb", "intransitive"]],
    ["気に入る", "to be pleased with, to like", "新しく買ったパソコンのデザインがとても気に入っている。", "I am very pleased with the design of my newly bought computer.", ["vocabulary", "verb", "intransitive"]],
    ["着替える", "to change clothes", "汗をかいたので、シャワーを浴びてから清潔な服に着替えた。", "Since I sweat a lot, I took a shower and changed into clean clothes.", ["vocabulary", "verb", "intransitive"]],
    ["効く", "to be effective, to work", "この薬は頭痛によく効くが、眠くなる副作用がある。", "This medicine is very effective for headaches, but it has the side effect of making you sleepy.", ["vocabulary", "verb", "intransitive"]],
    ["腐る", "to rot, to spoil", "冷蔵庫に入れ忘れたため、買ってきた肉が腐ってしまった。", "Because I forgot to put it in the refrigerator, the meat I bought spoiled.", ["vocabulary", "verb", "intransitive"]],
    ["組み立てる", "to assemble, to construct", "家具のパーツを説明書通りに組み立てるのに、二時間かかった。", "It took two hours to assemble the furniture parts according to the instructions.", ["vocabulary", "verb", "transitive"]],
    ["狂う", "to go mad, to get out of order", "急な仕様変更のせいで、プロジェクトのスケジュールがすっかり狂ってしまった。", "Because of the sudden specification change, the project schedule went completely out of order.", ["vocabulary", "verb", "intransitive"]],
    ["暮れる", "to get dark, to end", "議論に夢中になっているうちに、あっという間に日が暮れていた。", "While we were engrossed in the discussion, the sun went down before we knew it.", ["vocabulary", "verb", "intransitive"]],
    ["加える", "to add, to include", "スープの味が少し薄かったので、塩と胡椒を加えた。", "The soup tasted a bit weak, so I added some salt and pepper.", ["vocabulary", "verb", "transitive"]],
    ["削る", "to shave off, to cut down", "利益を確保するためには、無駄な経費を徹底的に削る必要がある。", "To secure profits, we need to thoroughly cut down on unnecessary expenses.", ["vocabulary", "verb", "transitive"]],
    ["越える", "to cross, to pass", "この山を越えれば、目的地はもうすぐそこだ。", "Once we cross this mountain, our destination is just around the corner.", ["vocabulary", "verb", "intransitive"]],
    ["凍る", "to freeze", "昨夜はかなり冷え込んだため、路面の水たまりが凍っている。", "Because it got quite cold last night, the puddles on the road are frozen.", ["vocabulary", "verb", "intransitive"]],
    ["腰掛ける", "to sit down", "待合室のベンチに腰掛けて、名前が呼ばれるのを待った。", "I sat down on a bench in the waiting room and waited for my name to be called.", ["vocabulary", "verb", "intransitive"]],
    ["こぼす", "to spill", "誤ってコーヒーをこぼし、大切な書類を汚してしまった。", "I accidentally spilled coffee and ruined some important documents.", ["vocabulary", "verb", "transitive"]],
    ["転がる", "to roll, to tumble", "子供のおもちゃが部屋の床のあちこちに転がっている。", "Children's toys are rolling about here and there on the room's floor.", ["vocabulary", "verb", "intransitive"]],
    ["壊す", "to break, to destroy", "古い建物を壊して、新しいマンションを建設する計画がある。", "There is a plan to tear down the old building and construct a new apartment complex.", ["vocabulary", "verb", "transitive"]],
    ["探る", "to search, to investigate", "市場の最新動向を探るため、競合他社の製品を分析する。", "We will analyze competitors' products to investigate the latest market trends.", ["vocabulary", "verb", "transitive"]],
    ["叫ぶ", "to shout, to yell", "環境保護の重要性が叫ばれているが、具体的な対策はまだ不十分だ。", "The importance of environmental protection is being shouted about, but concrete measures are still insufficient.", ["vocabulary", "verb", "intransitive"]],
    ["避ける", "to avoid", "通勤ラッシュの混雑を避けるため、早朝に出勤している。", "I commute early in the morning to avoid the congestion of the rush hour.", ["vocabulary", "verb", "transitive"]],
    ["冷ます", "to cool down", "お茶が熱すぎたので、少し冷ましてから飲んだ。", "The tea was too hot, so I let it cool down a bit before drinking it.", ["vocabulary", "verb", "transitive"]],
    ["覚める", "to wake up, to become sober", "休日は昼過ぎまで寝ていて、やっと目が覚めた。", "On my days off, I sleep until past noon, and I finally woke up.", ["vocabulary", "verb", "intransitive"]],
    ["去る", "to leave, to pass", "彼は一身上の都合により、先月末で会社を去った。", "He left the company at the end of last month due to personal reasons.", ["vocabulary", "verb", "intransitive"]],
    ["騒ぐ", "to make noise, to be excited", "夜遅くに大声で騒ぐのは、近所迷惑になるのでやめてください。", "Please stop making loud noise late at night, as it is a nuisance to the neighbors.", ["vocabulary", "verb", "intransitive"]],
    ["沈む", "to sink, to feel depressed", "あの豪華客船は、氷山に衝突して海の底に沈んでしまった。", "That luxury cruise ship collided with an iceberg and sank to the bottom of the sea.", ["vocabulary", "verb", "intransitive"]],
    ["縛る", "to tie, to bind", "古新聞をヒモでしっかりと縛ってから回収に出した。", "I tied up the old newspapers tightly with string before putting them out for collection.", ["vocabulary", "verb", "transitive"]],
    ["支払う", "to pay", "オンラインショッピングの代金をクレジットカードで支払った。", "I paid for the online shopping with a credit card.", ["vocabulary", "verb", "transitive"]],
    ["しまう", "to put away, to finish", "冬物のコートをクリーニングに出してからクローゼットにしまった。", "I put my winter coats away in the closet after taking them to the dry cleaners.", ["vocabulary", "verb", "transitive"]],
    ["示す", "to show, to point out", "このデータは、私たちのマーケティング戦略が正しいことを示している。", "This data shows that our marketing strategy is correct.", ["vocabulary", "verb", "transitive"]],
    ["占める", "to occupy, to account for", "高齢者が総人口に占める割合は、年々増加している。", "The percentage that the elderly account for in the total population is increasing year by year.", ["vocabulary", "verb", "transitive"]],
    ["湿る", "to become damp, to get wet", "梅雨の時期は洗濯物が乾きにくく、いつも少し湿っている気がする。", "During the rainy season, laundry is hard to dry, and it always feels a bit damp.", ["vocabulary", "verb", "intransitive"]],
    ["優れる", "to excel, to be excellent", "このスマートフォンは、特にカメラの性能において優れている。", "This smartphone is particularly excellent in terms of its camera performance.", ["vocabulary", "verb", "intransitive"]],
    ["済ませる", "to finish, to get it over with", "今日の昼食は、コンビニのおにぎりだけで簡単に済ませた。", "I simply got lunch over with today using just a convenience store rice ball.", ["vocabulary", "verb", "transitive"]],
    ["すれ違う", "to pass by each other, to disagree", "駅前で昔の同級生とすれ違ったが、相手は私に気付かなかったようだ。", "I passed by an old classmate in front of the station, but they didn't seem to notice me.", ["vocabulary", "verb", "intransitive"]],
    ["迫る", "to approach, to press", "プロジェクトの締め切りが明日に迫っており、チーム全員が残業している。", "The project deadline is approaching tomorrow, and the whole team is working overtime.", ["vocabulary", "verb", "intransitive"]],
    ["注ぐ", "to pour", "乾杯のために、グラスにシャンパンをなみなみと注いだ。", "I poured champagne to the brim of the glasses for a toast.", ["vocabulary", "verb", "transitive"]],
    ["備える", "to prepare, to furnish with", "万が一の自然災害に備えて、非常食と水を備蓄している。", "We are stockpiling emergency food and water to prepare for the unlikely event of a natural disaster.", ["vocabulary", "verb", "transitive"]],
    ["揃う", "to be complete, to gather", "必要な書類がすべて揃ってから、ビザの申請手続きを始めてください。", "Please start the visa application process after all the necessary documents are gathered.", ["vocabulary", "verb", "intransitive"]],
    ["倒す", "to throw down, to defeat", "誤って花瓶を倒し、テーブルの周りを水浸しにしてしまった。", "I accidentally knocked over the vase, flooding the area around the table with water.", ["vocabulary", "verb", "transitive"]],
    ["戦う", "to fight, to battle", "環境問題という地球規模の課題に対して、私たちは協力して戦わなければならない。", "We must fight together against the global challenge of environmental issues.", ["vocabulary", "verb", "intransitive"]],
    ["確かめる", "to confirm, to check", "メールを送信する前に、宛先と添付ファイルが正しいか必ず確かめてください。", "Before sending an email, please always check that the recipient and the attachment are correct.", ["vocabulary", "verb", "transitive"]],
    ["助かる", "to be saved, to be helped", "同僚がプレゼンの資料作りを手伝ってくれたおかげで、本当に助かった。", "I was really saved thanks to my colleague helping me make the presentation materials.", ["vocabulary", "verb", "intransitive"]],
    ["例える", "to liken to, to compare", "彼は人生をよく長い旅に例えて語る。", "He often likens life to a long journey when he speaks.", ["vocabulary", "verb", "transitive"]],
    ["頼る", "to rely on, to depend on", "問題が複雑な場合は、一人で抱え込まずに専門家に頼るべきだ。", "When a problem is complex, you should rely on an expert instead of dealing with it alone.", ["vocabulary", "verb", "transitive"]],
    ["違う", "to differ, to be wrong", "私の意見は彼の考えと少し違いますが、目的は同じです。", "My opinion differs slightly from his thoughts, but our goal is the same.", ["vocabulary", "verb", "intransitive"]],
    ["散らかる", "to be scattered, to be in a mess", "子供が遊んだ後で、部屋中におもちゃが散らかっている。", "Toys are scattered all over the room after the children played.", ["vocabulary", "verb", "intransitive"]],
    ["捕まえる", "to catch, to arrest", "警察は防犯カメラの映像を手がかりに、ついに犯人を捕まえた。", "The police finally caught the suspect using the security camera footage as a clue.", ["vocabulary", "verb", "transitive"]],
    ["尽きる", "to run out, to be exhausted", "長期のプロジェクトを終え、チームの体力と気力は限界まで尽きていた。", "Having finished the long-term project, the team's physical and mental strength were exhausted to the limit.", ["vocabulary", "verb", "intransitive"]],
    ["突く", "to thrust, to strike, to poke", "彼は会議中に核心を突く鋭い質問を投げかけた。", "During the meeting, he threw a sharp question that struck at the core of the issue.", ["vocabulary", "verb", "transitive"]],
    ["勤める", "to work for, to serve", "大学を卒業して以来、ずっと同じIT企業に勤めている。", "I have been working for the same IT company ever since graduating from university.", ["vocabulary", "verb", "intransitive"]],
    ["努める", "to try hard, to make an effort", "お客様に満足いただけるよう、サービスの向上に努めてまいります。", "We will make an effort to improve our services so that our customers will be satisfied.", ["vocabulary", "verb", "intransitive"]],
    ["繋ぐ", "to connect, to tie", "複数のパソコンをネットワークで繋いで、データを共有できるようにした。", "We connected multiple computers via a network to enable data sharing.", ["vocabulary", "verb", "transitive"]],
    ["潰す", "to crush, to smash, to waste", "暇を潰すために、カフェでスマートフォンを見ながら時間を過ごした。", "To kill time, I spent time at a cafe looking at my smartphone.", ["vocabulary", "verb", "transitive"]],
    ["積む", "to pile up, to accumulate", "海外の支社で数年間の経験を積むことが、昇進の条件となっている。", "Accumulating several years of experience at an overseas branch is a condition for promotion.", ["vocabulary", "verb", "transitive"]],
    ["詰める", "to pack, to stuff, to work out details", "旅行の荷物をスーツケースに詰めていたら、あっという間に夜中になっていた。", "While I was packing my travel luggage into the suitcase, it quickly became midnight.", ["vocabulary", "verb", "transitive"]],
    ["解く", "to solve, to untie", "この複雑な数学のパズルを自力で解くのにはかなりの時間がかかった。", "It took a considerable amount of time to solve this complex math puzzle on my own.", ["vocabulary", "verb", "transitive"]],
    ["飛ばす", "to fly, to skip", "プレゼンでは時間が足りず、最後の二つのスライドを飛ばすことになった。", "There wasn't enough time during the presentation, so I had to skip the last two slides.", ["vocabulary", "verb", "transitive"]],
    ["留まる", "to remain, to stay", "この製品の不具合は一部のロットに留まらず、全体に影響している可能性がある。", "The defects in this product might not be limited to a few lots but could be affecting all of them.", ["vocabulary", "verb", "intransitive"]],
    ["伴う", "to accompany, to involve", "大規模なシステム改修には、常に予期せぬリスクが伴うものだ。", "Large-scale system revisions always involve unexpected risks.", ["vocabulary", "verb", "intransitive"]],
    ["眺める", "to look at, to gaze at", "山頂から眼下に広がる街の景色を静かに眺めた。", "I quietly gazed at the view of the city spreading out below from the summit.", ["vocabulary", "verb", "transitive"]],
    ["流れる", "to flow, to be washed away", "街角からどこか懐かしいクリスマスソングが流れてきた。", "A somewhat nostalgic Christmas song came flowing from the street corner.", ["vocabulary", "verb", "intransitive"]],
    ["鳴らす", "to ring, to sound", "自転車で歩道を走る際、みだりにベルを鳴らすのはマナー違反だ。", "When riding a bicycle on the sidewalk, ringing the bell indiscriminately is bad manners.", ["vocabulary", "verb", "transitive"]],
    ["似合う", "to suit, to match", "その明るい色のドレスは、彼女の雰囲気にとてもよく似合っている。", "That bright-colored dress suits her aura very well.", ["vocabulary", "verb", "intransitive"]],
    ["抜く", "to pull out, to extract, to omit", "虫歯がひどく痛むので、とうとう歯医者で抜いてもらった。", "My cavity hurt so badly that I finally had it pulled out by the dentist.", ["vocabulary", "verb", "transitive"]],
    ["狙う", "to aim at", "我々の新製品は、主に二十代の若い女性の市場を狙っている。", "Our new product is primarily aiming at the market of young women in their twenties.", ["vocabulary", "verb", "transitive"]],
    ["残す", "to leave (behind)", "食べ物を粗末にしないよう、お皿の料理は残さずきれいに食べた。", "To avoid wasting food, I ate everything on my plate without leaving anything behind.", ["vocabulary", "verb", "transitive"]],
    ["乗せる", "to place on, to give a ride", "荷物を車のトランクに乗せて、すぐに出発する準備を整えた。", "I placed the luggage in the trunk of the car and got ready to depart immediately.", ["vocabulary", "verb", "transitive"]],
    ["省く", "to omit, to save", "会議の時間を短縮するため、今回は自己紹介のプロセスを省くことにした。", "To shorten the meeting time, we decided to omit the self-introduction process this time.", ["vocabulary", "verb", "transitive"]],
    ["外す", "to unfasten, to remove, to slip away", "今、担当者は席を外しておりますので、後ほど折り返しお電話いたします。", "The person in charge is away from their desk right now, so we will call you back later.", ["vocabulary", "verb", "transitive"]],
    ["離れる", "to separate from, to leave", "親元を離れて一人暮らしを始めると、家事の大変さがよくわかる。", "When you leave your parents' home and start living alone, you clearly understand how difficult chores are.", ["vocabulary", "verb", "intransitive"]],
    ["省みる", "to reflect on", "過去の失敗を省みることで、同じ間違いを繰り返さないようにする。", "By reflecting on past failures, I try to avoid repeating the same mistakes.", ["vocabulary", "verb", "transitive"]],
    ["流行る", "to be popular, to spread", "最近、若者の間でレトロなデザインのカメラが流行っているそうだ。", "I hear that retro-designed cameras are popular among young people recently.", ["vocabulary", "verb", "intransitive"]],
    ["引き受ける", "to undertake, to take on", "彼は誰もやりたがらない面倒な仕事を、いつも快く引き受けてくれる。", "He always willingly takes on the troublesome tasks that no one else wants to do.", ["vocabulary", "verb", "transitive"]],
    ["引き返す", "to turn back", "途中で忘れ物に気付き、慌てて家まで引き返した。", "I realized I forgot something on the way and hurriedly turned back home.", ["vocabulary", "verb", "intransitive"]],
    ["防ぐ", "to prevent", "ウイルスの感染を防ぐためには、こまめな手洗いと換気が重要です。", "To prevent virus infection, frequent hand washing and ventilation are important.", ["vocabulary", "verb", "transitive"]],
    ["振る", "to wave, to shake, to reject", "空港で友人を見送る際、姿が見えなくなるまで大きく手を振った。", "When seeing my friend off at the airport, I waved my hand widely until they were out of sight.", ["vocabulary", "verb", "transitive"]],
    ["触れる", "to touch, to mention", "美術館の展示作品には、絶対に手を触れないでください。", "Please do not ever touch the exhibited artworks in the museum.", ["vocabulary", "verb", "intransitive"]],
    ["減らす", "to decrease, to reduce", "プラスチックごみを減らすため、マイバッグの利用が推奨されている。", "To reduce plastic waste, the use of reusable bags is recommended.", ["vocabulary", "verb", "transitive"]],
    ["吠える", "to bark, to howl", "見知らぬ人が近づいてきたので、飼い犬が激しく吠え始めた。", "Because a stranger approached, the pet dog began to bark violently.", ["vocabulary", "verb", "intransitive"]],
    ["誇る", "to boast of, to be proud of", "このホテルは、市内で最も美しい夜景を誇っています。", "This hotel boasts the most beautiful night view in the city.", ["vocabulary", "verb", "transitive"]],
    ["任せる", "to entrust to", "このプロジェクトの進行は、経験豊富な彼にすべて任せるのが一番安心だ。", "It is most reassuring to entrust the progress of this project entirely to him, as he is highly experienced.", ["vocabulary", "verb", "transitive"]],
    ["曲げる", "to bend, to twist", "どうしても自分の信念を曲げることができず、彼は会社を辞める道を選んだ。", "Unable to bend his beliefs no matter what, he chose the path of quitting the company.", ["vocabulary", "verb", "transitive"]],
    ["交ざる", "to be mixed", "白いペンキに少し青色が交ざり、きれいな水色になった。", "A little blue mixed into the white paint, becoming a pretty light blue.", ["vocabulary", "verb", "intransitive"]],
    ["増す", "to increase, to grow", "締め切りが近づくにつれて、チーム内の緊張感がさらに増してきた。", "As the deadline approached, the tension within the team grew even more.", ["vocabulary", "verb", "intransitive"]],
    ["招く", "to invite, to cause", "彼の不用意な発言が、周囲の大きな誤解を招いてしまった。", "His careless remark caused a major misunderstanding among those around him.", ["vocabulary", "verb", "transitive"]],
    ["迷う", "to get lost, to hesitate", "二つの魅力的なオファーがあり、どちらの会社に転職するか深く迷っている。", "I have two attractive offers, and I am deeply hesitating over which company to switch to.", ["vocabulary", "verb", "intransitive"]],
    ["見直す", "to look again, to review, to reconsider", "業務の効率化を図るため、これまでのマニュアルを根本から見直すことになった。", "To aim for operational efficiency, we decided to thoroughly review our previous manuals from the ground up.", ["vocabulary", "verb", "transitive"]],
    ["向ける", "to turn towards, to point", "新製品のターゲットを若年層だけでなく、シニア層にも向ける方針だ。", "We have a policy to direct the target of the new product not only at the youth demographic but also at seniors.", ["vocabulary", "verb", "transitive"]],
    ["儲かる", "to be profitable", "この新しいビジネスモデルは、初期投資が少なくても十分に儲かる可能性がある。", "This new business model has the potential to be sufficiently profitable even with a small initial investment.", ["vocabulary", "verb", "intransitive"]],
    ["燃やす", "to burn", "落ち葉を集めて庭で燃やすのは、現在では禁止されている地域が多い。", "Gathering fallen leaves and burning them in the garden is prohibited in many areas nowadays.", ["vocabulary", "verb", "transitive"]],
    ["戻す", "to return, to put back", "使った後の道具は、必ず元の場所に戻しておいてください。", "Please make sure to put the tools back in their original place after using them.", ["vocabulary", "verb", "transitive"]],
    ["訳す", "to translate", "この英語の技術文書を、明日までに日本語に訳す必要があります。", "I need to translate this English technical document into Japanese by tomorrow.", ["vocabulary", "verb", "transitive"]],
    ["雇う", "to employ, to hire", "繁忙期に備えて、臨時のアルバイトスタッフを数名雇うことにした。", "In preparation for the busy season, we decided to hire several temporary part-time staff.", ["vocabulary", "verb", "transitive"]],
    ["破る", "to tear, to break (a promise)", "彼は絶対に秘密を守ると言っていたのに、あっさりと約束を破った。", "Even though he said he would absolutely keep the secret, he easily broke his promise.", ["vocabulary", "verb", "transitive"]],
    ["譲る", "to assign, to hand over, to yield", "電車の中でお年寄りに席を譲るのは、当たり前のマナーです。", "Yielding your seat to an elderly person on the train is simple common courtesy.", ["vocabulary", "verb", "transitive"]],
    ["許す", "to permit, to forgive", "システムのセキュリティ制限により、外部からのアクセスは許されていない。", "Due to the system's security restrictions, access from the outside is not permitted.", ["vocabulary", "verb", "transitive"]],
    ["分ける", "to divide, to share", "参加者を三つのグループに分けて、それぞれ別のテーマで議論を行った。", "We divided the participants into three groups and had them discuss different topics.", ["vocabulary", "verb", "transitive"]],
    ["打ち合わせる", "to discuss, to arrange", "明日のクライアント訪問について、事前に詳細を打ち合わせる必要がある。", "We need to discuss the details in advance regarding tomorrow's client visit.", ["vocabulary", "verb", "compound verb"]],
    ["切り替える", "to switch, to change over", "失敗を引きずらず、気持ちを切り替えて次のプロジェクトに取り組もう。", "Let's not dwell on the failure, but switch our mindset and tackle the next project.", ["vocabulary", "verb", "compound verb"]],
    ["心掛ける", "to bear in mind, to aim to do", "健康のため、普段からバランスの良い食事と適度な運動を心掛けている。", "For the sake of my health, I always bear in mind to eat a balanced diet and exercise moderately.", ["vocabulary", "verb", "compound verb"]],
    ["問い合わせる", "to inquire", "商品の在庫状況について、カスタマーサポートに電話で問い合わせた。", "I inquired with customer support by phone regarding the stock status of the product.", ["vocabulary", "verb", "compound verb"]],
    ["取り消す", "to cancel, to withdraw", "天候の悪化が予想されるため、週末のフライトを泣く泣く取り消した。", "Because bad weather was forecasted, I reluctantly canceled my weekend flight.", ["vocabulary", "verb", "compound verb"]],
    ["見当たる", "to be found", "いくら探しても、昨日デスクの上に置いたはずの書類が見当たらない。", "No matter how much I search, I can't find the documents that I'm sure I left on my desk yesterday.", ["vocabulary", "verb", "compound verb"]],
    ["申し込む", "to apply for, to propose", "人気の語学講座の定員が埋まる前に、急いでインターネットから申し込んだ。", "Before the popular language course filled up to capacity, I quickly applied online.", ["vocabulary", "verb", "compound verb"]],
    ["あくまで", "to the end, persistently, strictly", "これはあくまで私の個人的な意見であり、会社の公式な見解ではありません。", "This is strictly my personal opinion and not the official view of the company.", ["vocabulary", "adverb"]],
    ["案外", "unexpectedly", "難しいと思っていた試験だが、受けてみると案外簡単に解くことができた。", "It was an exam I thought would be difficult, but upon taking it, I was able to solve it unexpectedly easily.", ["vocabulary", "adverb"]],
    ["いちいち", "one by one, every single time", "彼は私のやり方にいちいち文句をつけてくるので、本当にうんざりする。", "He complains about my way of doing things every single time, which is really exhausting.", ["vocabulary", "adverb"]],
    ["思い切って", "resolutely, taking the plunge", "ずっと悩んでいたが、思い切って彼に真実を伝えることにした。", "I had been agonizing over it for a long time, but I took the plunge and decided to tell him the truth.", ["vocabulary", "adverb"]],
    ["かえって", "on the contrary, rather", "親切のつもりで手伝ったのに、かえって彼らの邪魔をしてしまったようだ。", "I helped with the intention of being kind, but it seems I rather got in their way.", ["vocabulary", "adverb"]],
    ["必ずしも", "(not) always, (not) necessarily", "価格が高い商品が必ずしも品質が良いとは限らないので注意が必要だ。", "You need to be careful because an expensive product does not necessarily mean its quality is good.", ["vocabulary", "adverb"]],
    ["さっぱり", "feeling refreshed, completely (not)", "彼が何を言いたいのか、私にはさっぱり理解できなかった。", "I could not completely understand what he was trying to say.", ["vocabulary", "adverb"]],
    ["しいんと", "silently, quietly", "先生が教室に入ってくると、騒いでいた生徒たちはしいんと静まり返った。", "When the teacher entered the classroom, the noisy students fell dead silent.", ["vocabulary", "adverb"]],
    ["せっかく", "with trouble, at great pains", "せっかく海まで来たのに、雨のせいで泳ぐことができなくて残念だ。", "It's a shame that even though we took the trouble to come to the sea, we couldn't swim because of the rain.", ["vocabulary", "adverb"]],
    ["絶対", "absolutely, definitely", "このプロジェクトは今後の会社の命運を握っているので、絶対に失敗できない。", "Because this project holds the future fate of the company, we absolutely cannot afford to fail.", ["vocabulary", "adverb"]],
    ["そっと", "softly, gently, secretly", "子供が寝ているので、足音を立てないようにそっと部屋を出た。", "Because the child was sleeping, I gently left the room so as not to make footsteps.", ["vocabulary", "adverb"]],
    ["ただち（に）", "immediately, at once", "機械に異常を知らせるランプが点灯したら、ただちに運転を停止してください。", "If the light warning of a machine abnormality turns on, please stop operation immediately.", ["vocabulary", "adverb"]],
    ["たまらない", "unbearable, irresistible", "真夏の炎天下での作業は、暑くてたまらない。", "Working under the blazing sun in midsummer is unbearably hot.", ["vocabulary", "adverb"]],
    ["ついに", "finally, at last", "何年もの厳しい研究を経て、ついに新しい特効薬が完成した。", "After years of rigorous research, the new miracle drug was finally completed.", ["vocabulary", "adverb"]],
    ["常に", "always, constantly", "プロのスポーツ選手は、常にベストなコンディションを保つ努力をしている。", "Professional athletes are constantly making an effort to maintain their best condition.", ["vocabulary", "adverb"]],
    ["とうとう", "finally, at last", "長年使ってきた愛用のパソコンが、とうとう動かなくなってしまった。", "My beloved computer that I've used for many years has finally stopped working.", ["vocabulary", "adverb"]],
    ["どうしても", "by all means, no matter what", "どうしてもこのソフトウェアのバグの原因がわからず、開発が行き詰まっている。", "No matter what, I can't figure out the cause of this software bug, and development has stalled.", ["vocabulary", "adverb"]],
    ["どっと", "suddenly, abruptly", "有名なコメディアンがステージに登場すると、客席からどっと笑いが起きた。", "When the famous comedian appeared on stage, a sudden burst of laughter arose from the audience.", ["vocabulary", "adverb"]],
    ["共に", "together, with", "私たちはこの困難な状況を、チーム全員で共に乗り越えなければならない。", "We must overcome this difficult situation together with the whole team.", ["vocabulary", "adverb"]],
    ["なんとか", "somehow, managing to", "締切ギリギリだったが、なんとかレポートを提出することができて安心した。", "It was right at the deadline, but I felt relieved that I somehow managed to submit the report.", ["vocabulary", "adverb"]],
    ["にこにこ", "smilingly", "彼女はいつもにこにこしていて、周囲を明るい雰囲気にさせてくれる。", "She is always smiling and brings a bright atmosphere to her surroundings.", ["vocabulary", "adverb"]],
    ["はきはき", "briskly, clearly", "面接では、面接官の質問に対してはきはきと答えることが好印象につながる。", "In an interview, answering the interviewer's questions clearly leads to a good impression.", ["vocabulary", "adverb"]],
    ["ばったり", "unexpectedly (meeting someone)", "出張先のロビーで、数年ぶりに前の職場の同僚とばったり出会った。", "In the lobby of my business trip destination, I unexpectedly ran into a colleague from my previous workplace for the first time in years.", ["vocabulary", "adverb"]],
    ["ふと", "suddenly, accidentally", "電車の中で外の景色を眺めていると、ふと昔の楽しかった出来事を思い出した。", "Looking at the scenery outside on the train, I suddenly remembered a fun event from the past.", ["vocabulary", "adverb"]],
    ["ほぼ", "almost, roughly", "新しいシステムの開発作業は、予定通りほぼ完了している。", "The development work for the new system is almost complete, just as scheduled.", ["vocabulary", "adverb"]],
    ["まさか", "by no means, never", "まさか彼のような誠実な人が、会社の資金を横領していたなんて信じられない。", "I can't believe that a sincere person like him would ever embezzle company funds.", ["vocabulary", "adverb"]],
    ["ますます", "increasingly, more and more", "インターネットの普及により、情報セキュリティの重要性はますます高まっている。", "With the spread of the internet, the importance of information security is becoming increasingly higher.", ["vocabulary", "adverb"]],
    ["まるで", "quite, entirely, completely, as if", "そのCG技術で作られた映像は、まるで本物の風景のようにリアルだった。", "The video created with that CG technology was so realistic that it was as if it were real scenery.", ["vocabulary", "adverb"]],
    ["自ら", "for one's self, personally", "彼は部下に任せるだけでなく、自らも現場に立って問題解決にあたった。", "He didn't just leave it to his subordinates; he personally stood at the site to solve the problem.", ["vocabulary", "adverb"]],
    ["むしろ", "rather, better, instead", "予算を削って品質を下げるくらいなら、むしろ計画を延期した方がいい。", "If we're going to lower the quality by cutting the budget, it would be rather better to postpone the plan.", ["vocabulary", "adverb"]],
    ["めっきり", "remarkably, noticeably", "十一月に入ってから、朝晩の冷え込みがめっきり厳しくなってきた。", "Since entering November, the chill in the mornings and evenings has become noticeably severe.", ["vocabulary", "adverb"]],
    ["最も", "most, extremely", "健康を維持する上で、十分な睡眠をとることが最も重要だと医師に言われた。", "The doctor told me that getting enough sleep is the most important thing for maintaining health.", ["vocabulary", "adverb"]],
    ["やがて", "before long, soon", "空を覆っていた厚い雲もやがて晴れ、美しい星空が見えてくるだろう。", "The thick clouds covering the sky will soon clear, and a beautiful starry sky will likely become visible.", ["vocabulary", "adverb"]],
    ["やや", "a little, slightly", "今年の冬の平均気温は、例年に比べてやや高い傾向にあるそうだ。", "It seems that the average temperature this winter is trending slightly higher than in typical years.", ["vocabulary", "adverb"]],
    ["わざと", "on purpose, intentionally", "子供は親の気を引くために、わざと大きな音を立てておもちゃを落とした。", "The child intentionally dropped the toy with a loud noise to catch their parents' attention.", ["vocabulary", "adverb"]],
    ["わざわざ", "expressly, taking the trouble", "こんな遠くまでわざわざお越しいただき、誠にありがとうございます。", "Thank you very much for taking the trouble to come all the way here.", ["vocabulary", "adverb"]],
    ["あいにく", "unfortunately", "あいにく担当の者は本日は終日外出しております。", "Unfortunately, the person in charge is out for the whole day today.", ["vocabulary", "adverb"]],
    ["いかにも", "indeed, really, evidently", "彼の話し方はいかにも自信に満ち溢れているように聞こえる。", "His way of speaking sounds as if he is indeed full of confidence.", ["vocabulary", "adverb"]],
    ["いつの間にか", "before one knows it", "夢中で本を読んでいるうちに、いつの間にか外は真っ暗になっていた。", "While I was engrossed in reading the book, the outside had become pitch dark before I knew it.", ["vocabulary", "adverb"]],
    ["大いに", "very much, greatly", "今回の成功は、チームメンバーの協力によるところが大いにあります。", "This success relies greatly on the cooperation of the team members.", ["vocabulary", "adverb"]],
    ["およそ", "about, roughly", "この古い神社の歴史は、およそ千年以上前に遡ると言われている。", "It is said that the history of this old shrine dates back roughly over a thousand years.", ["vocabulary", "adverb"]],
    ["かなり", "considerably, fairly", "昨夜は遅くまで残業したため、今朝はかなり疲労が溜まっている。", "Because I worked overtime until late last night, I have a considerable amount of fatigue accumulated this morning.", ["vocabulary", "adverb"]],
    ["くれぐれも", "repeatedly, sincerely", "これから寒くなりますので、くれぐれもお体にはお気をつけください。", "It will get cold from now on, so please sincerely take care of your health.", ["vocabulary", "adverb"]],
    ["こっそり", "stealthily, secretly", "ダイエット中なのに、夜中にこっそり冷蔵庫のアイスを食べてしまった。", "Even though I'm on a diet, I secretly ate ice cream from the fridge in the middle of the night.", ["vocabulary", "adverb"]],
    ["このごろ", "recently, nowadays", "このごろはリモートワークが普及し、自宅で仕事をする人が急増した。", "Recently, remote work has spread, and the number of people working at home has rapidly increased.", ["vocabulary", "adverb"]],
    ["さらに", "furthermore, again", "製品の安全性を高めるために、さらに厳しいテストを実施する予定だ。", "To enhance the safety of the product, we plan to conduct even further strict testing.", ["vocabulary", "adverb"]],
    ["次々（に）", "one after another", "スマートフォンの新機能が次々と発表され、技術の進歩に驚かされる。", "New smartphone features are being announced one after another, and I am amazed by the progress of technology.", ["vocabulary", "adverb"]],
    ["とりあえず", "for now, first of all", "まだ詳細な計画は決まっていないが、とりあえず必要な機材だけは手配しておこう。", "The detailed plan is not yet decided, but for now, let's just arrange for the necessary equipment.", ["vocabulary", "adverb"]],
    ["どうせ", "anyhow, in any case", "どうせやるなら、中途半端に終わらせず、徹底的に最高のものを作りたい。", "If we're going to do it anyhow, I want to make the best thing thoroughly, instead of leaving it halfway done.", ["vocabulary", "adverb"]],
    ["なお", "furthermore, still", "この書類の提出期限は明日ですが、なお、変更がある場合はすぐにご連絡ください。", "The deadline for this document is tomorrow; furthermore, please contact us immediately if there are any changes.", ["vocabulary", "adverb"]],
    ["なるべく", "as much as possible", "環境への負担を減らすため、なるべく公共交通機関を利用するようにしている。", "To reduce the burden on the environment, I try to use public transportation as much as possible.", ["vocabulary", "adverb"]],
    ["なぜなら", "because", "彼女の提案を採用することにした。なぜなら、最も現実的でコストが低いからだ。", "We decided to adopt her proposal. This is because it is the most realistic and has the lowest cost.", ["vocabulary", "adverb"]],
    ["にわかに", "suddenly", "空がにわかに暗くなり、大粒の雨が激しく降り始めた。", "The sky suddenly turned dark, and large drops of rain began to fall heavily.", ["vocabulary", "adverb"]],
    ["はたして", "as was expected, really", "AI技術の発展は、はたして人類に幸福をもたらすのだろうか。", "Will the development of AI technology really bring happiness to humanity?", ["vocabulary", "adverb"]],
    ["まもなく", "soon, before long", "まもなく三番線に、東京行きの特急列車が到着いたします。", "Before long, the limited express train bound for Tokyo will arrive at track three.", ["vocabulary", "adverb"]],
    ["めったに", "rarely", "彼は非常に温厚な性格で、職場で怒ることはめったにない。", "He has a very mild-mannered personality, and he rarely gets angry at the workplace.", ["vocabulary", "adverb"]],
    ["割と", "relatively, comparatively", "あの店のランチは、値段が安い割にボリュームがあって美味しいと評判だ。", "That restaurant's lunch is reputed to be relatively generous in portion and tasty for its low price.", ["vocabulary", "adverb"]],
    ["思わず", "unintentionally, spontaneously", "映画の感動的なラストシーンを見て、思わず涙がこぼれてしまった。", "Watching the moving final scene of the movie, tears unintentionally spilled from my eyes.", ["vocabulary", "adverb"]]
];

const cards = data.slice(0, 180).map((item, index) => {
    let [front, back, ex_jp, ex_en, tags] = item;
    
    // Fix any potential typo
    if (ex_en.includes("getting enough sleep is getting enough sleep")) {
        ex_en = "The doctor told me that getting enough sleep is the most important thing for maintaining health.";
    }

    const id = `n2-vocab-b-${String(index + 1).padStart(3, '0')}`;
    return {
        id,
        category: "vocabulary",
        front,
        back,
        exampleJp: ex_jp,
        exampleTranslation: ex_en,
        tags
    };
});

const outputJSON = {
    shardId: "n2-vocab-b-verbs-adv-expressions-180",
    level: "N2",
    language: "en",
    cards
};

const outDir = path.join(__dirname, '..', 'data', 'curated-packs', 'en', 'intake', 'n2');
const outPath = path.join(outDir, 'vocab_b_verbs_adv_expressions_180.json');

if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
}

fs.writeFileSync(outPath, JSON.stringify(outputJSON, null, 2), 'utf-8');
console.log(`Successfully generated ${cards.length} cards at ${outPath}`);
