import json
import os

shard = {
    "shardId": "n2-vocab-d-media-economy-environment-180",
    "level": "N2",
    "language": "en",
    "cards": []
}

def create_card(id_num, front, back, ex_jp, ex_en, tags):
    card_id = f"n2-vocab-d-{id_num:03d}"
    return {
        "id": card_id,
        "category": "vocabulary",
        "front": front,
        "back": back,
        "exampleJp": ex_jp,
        "exampleTranslation": ex_en,
        "tags": tags
    }

items = [
    ("報道", "report, journalism", "最新の報道によると、被害者の数はさらに増える見込みだ。", "According to the latest reports, the number of victims is expected to increase further.", ["media", "news"]),
    ("取材", "coverage, interview", "あのジャーナリストは、戦場での危険な取材で知られている。", "That journalist is known for his dangerous coverage in war zones.", ["media", "news"]),
    ("中継", "broadcast, relay", "オリンピックの開会式は世界中に生中継された。", "The opening ceremony of the Olympics was broadcast live worldwide.", ["media", "news"]),
    ("見出し", "headline", "新聞の大きな見出しを見て、思わず足を止めた。", "I stopped in my tracks when I saw the large newspaper headline.", ["media", "news"]),
    ("記事", "article", "彼が書いた経済に関する記事が、今朝の朝刊に載っている。", "The article he wrote about the economy is published in this morning's paper.", ["media", "news"]),
    ("発行", "issue, publication", "この雑誌は月に二回発行されている。", "This magazine is published twice a month.", ["media", "news"]),
    ("特集", "special feature", "今月の旅行雑誌は、ヨーロッパの古い街並みを特集している。", "This month's travel magazine features a special on old European townscapes.", ["media", "news"]),
    ("世論", "public opinion", "政府は世論の動向を慎重に見極める必要がある。", "The government needs to carefully assess the trends in public opinion.", ["media", "news"]),
    ("評論", "criticism, review", "彼の映画評論は鋭い視点が多く、読者から高く評価されている。", "His film reviews offer many sharp perspectives and are highly regarded by readers.", ["media", "news"]),
    ("司会", "moderator, hosting", "その討論会の司会を務めるのは、有名なベテランアナウンサーだ。", "The moderator for that debate is a famous veteran announcer.", ["media", "news"]),
    ("出版", "publishing", "彼女のデビュー小説は来月、大手の出版社から出版される。", "Her debut novel will be published by a major publishing company next month.", ["media", "news"]),
    ("広告", "advertisement", "インターネット上の広告費が、テレビ広告を上回る時代になった。", "We are now in an era where internet advertising expenses exceed television advertising.", ["media", "business"]),
    ("放送", "broadcasting", "台風の接近に伴い、緊急の気象情報が放送された。", "With the approach of the typhoon, urgent weather information was broadcast.", ["media", "disaster"]),
    ("収録", "recording", "このテレビ番組の収録は、観客を入れずに行われた。", "The recording of this TV program was conducted without a live audience.", ["media", "entertainment"]),
    ("記者", "journalist, reporter", "記者の厳しい質問に対し、大臣は言葉を濁した。", "The minister gave a vague answer to the reporter's tough question.", ["media", "news"]),
    ("ジャーナリスト", "journalist", "彼はフリーのジャーナリストとして、世界各地の紛争地帯を取材している。", "As a freelance journalist, he covers conflict zones all over the world.", ["media", "news"]),
    ("コメンテーター", "commentator", "ニュース番組のコメンテーターが、政治家の発言について鋭く批判した。", "The news program commentator sharply criticized the politician's remarks.", ["media", "news"]),
    ("マスコミ", "mass media", "その事件は、連日マスコミによって大々的に報じられている。", "The incident is being extensively covered by the mass media every day.", ["media", "news"]),
    ("視聴率", "audience rating", "最終回の視聴率が予想を大幅に上回り、制作陣は喜んでいる。", "The production team is thrilled that the final episode's audience rating far exceeded expectations.", ["media", "entertainment"]),
    ("生放送", "live broadcast", "生放送中の突然のハプニングに、スタジオは一時騒然となった。", "The studio briefly fell into chaos due to a sudden mishap during the live broadcast.", ["media", "entertainment"]),
    ("独占", "monopoly, exclusive", "その雑誌は、人気俳優の結婚に関する独占インタビューを掲載した。", "The magazine published an exclusive interview regarding the popular actor's marriage.", ["media", "business"]),
    ("匿名", "anonymous", "ネット上の匿名の書き込みが、思わぬトラブルを引き起こすことがある。", "Anonymous posts on the internet can sometimes cause unexpected trouble.", ["media", "technology"]),
    ("投稿", "post, contribution", "読者からの投稿欄には、様々な世代の意見が寄せられている。", "Opinions from various generations have been sent to the reader contribution column.", ["media", "news"]),
    ("掲載", "publication, posting", "論文が有名な学術誌に掲載され、彼の研究が世界に認められた。", "His paper was published in a famous academic journal, and his research was recognized globally.", ["media", "academic"]),
    ("速報", "breaking news", "地震の発生を伝える速報が、画面の上部にテロップで流れた。", "A breaking news ticker announcing the earthquake scrolled across the top of the screen.", ["media", "disaster"]),
    ("伝達", "transmission, communication", "災害時には、正確な情報の迅速な伝達が何より重要となる。", "In times of disaster, the rapid transmission of accurate information is paramount.", ["media", "communication"]),
    ("普及", "spread, diffusion", "スマートフォンの急速な普及により、人々の生活は大きく変化した。", "The rapid spread of smartphones has significantly changed people's lives.", ["technology", "society"]),
    ("インタビュー", "interview", "試合後のインタビューで、選手は涙を流してファンに感謝を伝えた。", "In the post-match interview, the player teared up and expressed gratitude to the fans.", ["media", "sports"]),
    ("取材陣", "press corps", "空港には、海外から帰国する代表チームを待ち受ける取材陣が殺到した。", "A horde of reporters flooded the airport waiting for the national team to return from overseas.", ["media", "news"]),
    ("記者会見", "press conference", "企業の不祥事に関する緊急の記者会見が、午後から開かれる。", "An emergency press conference regarding the corporate scandal will be held this afternoon.", ["media", "business"]),

    ("景気", "economic condition", "政府は景気の回復に向けて、新たな経済対策を発表した。", "The government announced new economic measures aiming for economic recovery.", ["economy", "business"]),
    ("利益", "profit", "新製品の売上が好調で、今期は過去最高の利益を記録しそうだ。", "Sales of the new product are strong, and we are likely to record record-high profits this term.", ["economy", "business"]),
    ("資本", "capital", "海外進出のためには、莫大な資本と優秀な人材が必要不可欠だ。", "Enormous capital and excellent human resources are essential for overseas expansion.", ["economy", "business"]),
    ("投資", "investment", "将来の成長を見込んで、再生可能エネルギーの分野に積極的に投資する。", "Anticipating future growth, we will actively invest in the renewable energy sector.", ["economy", "business"]),
    ("予算", "budget", "プロジェクトの予算が大幅に削減され、計画の見直しを余儀なくされた。", "The project budget was significantly reduced, forcing us to revise our plans.", ["economy", "business"]),
    ("赤字", "deficit", "長引く不況の影響で、多くの企業が赤字経営に苦しんでいる。", "Due to the prolonged recession, many companies are suffering from deficit operations.", ["economy", "business"]),
    ("黒字", "surplus", "経営陣の努力により、会社はついに数年ぶりの黒字に転換した。", "Thanks to the management team's efforts, the company finally turned a surplus for the first time in years.", ["economy", "business"]),
    ("経費", "expenses", "出張先での宿泊費や交通費などの経費は、後日会社から支給される。", "Expenses such as accommodation and travel costs during the business trip will be reimbursed by the company later.", ["economy", "business"]),
    ("株価", "stock price", "中央銀行の金利引き上げのニュースを受け、株価が急落した。", "Following the news of the central bank raising interest rates, stock prices plummeted.", ["economy", "business"]),
    ("倒産", "bankruptcy", "主要取引先の突然の倒産により、自社の経営も危機に陥った。", "Due to the sudden bankruptcy of a major business partner, our own management fell into a crisis.", ["economy", "business"]),
    ("雇用", "employment", "新しい工場の建設により、地域に数百人の雇用が創出されると期待されている。", "The construction of the new factory is expected to create hundreds of employment opportunities in the region.", ["economy", "society"]),
    ("解雇", "dismissal", "彼は会社の機密情報を漏洩したため、懲戒解雇処分となった。", "He was subjected to disciplinary dismissal for leaking confidential company information.", ["economy", "business"]),
    ("業績", "business performance", "海外市場での販売が好調で、今四半期の業績は予想を上回った。", "With strong sales in overseas markets, business performance this quarter exceeded expectations.", ["economy", "business"]),
    ("売上", "sales", "年末商戦に向けたキャンペーンが成功し、今月の売上は飛躍的に伸びた。", "The campaign for the year-end shopping season was successful, and this month's sales grew dramatically.", ["economy", "business"]),
    ("契約", "contract", "両社は新しい技術の共同開発に関する契約を正式に締結した。", "The two companies formally concluded a contract regarding the joint development of new technology.", ["economy", "business"]),
    ("借金", "debt", "事業の失敗で作った多額の借金を返すため、彼は昼夜問わず働いている。", "He is working day and night to pay off the heavy debt incurred from his business failure.", ["economy", "personal finance"]),
    ("取引", "transaction, trade", "海外の企業との取引では、文化や商習慣の違いを理解することが重要だ。", "In transactions with overseas companies, it is important to understand cultural and business practice differences.", ["economy", "business"]),
    ("為替", "foreign exchange", "為替レートの変動は、輸出企業の利益に直結する重要な問題だ。", "Fluctuations in foreign exchange rates are a critical issue directly linked to the profits of export companies.", ["economy", "business"]),
    ("融資", "loan, financing", "新規事業を立ち上げるため、銀行に融資を申し込む準備を進めている。", "We are preparing to apply for a loan from the bank to launch a new business.", ["economy", "business"]),
    ("金融", "finance", "世界的な金融危機により、多くの銀行が深刻な経営難に陥った。", "Due to the global financial crisis, many banks fell into severe managerial difficulties.", ["economy", "business"]),
    ("預金", "deposit", "将来の不安に備えて、毎月少しずつ銀行に預金をしている。", "I am making small monthly deposits in the bank to prepare for future uncertainties.", ["economy", "personal finance"]),
    ("利子", "interest", "現在の低い金利では、銀行にお金を預けてもほとんど利子はつかない。", "With current low interest rates, you earn almost no interest even if you leave your money in the bank.", ["economy", "finance"]),
    ("破産", "bankruptcy", "ギャンブルへの依存が原因で、彼は最終的に自己破産を申請した。", "Due to his gambling addiction, he ultimately filed for personal bankruptcy.", ["economy", "legal"]),
    ("税金", "tax", "国民から集められた税金は、道路の整備や社会福祉などに使われる。", "Taxes collected from citizens are used for road maintenance, social welfare, and other public services.", ["economy", "politics"]),
    ("節税", "tax saving", "企業は法律で認められた範囲内で、様々な節税対策を行っている。", "Companies implement various tax-saving measures within the boundaries allowed by the law.", ["economy", "business"]),
    ("輸出", "export", "この国は自動車や電子部品を海外へ輸出することで経済を支えている。", "This country supports its economy by exporting automobiles and electronic components overseas.", ["economy", "trade"]),
    ("輸入", "import", "原材料の多くを海外からの輸入に頼っているため、価格変動のリスクが高い。", "Because we rely heavily on imports from overseas for raw materials, the risk of price fluctuation is high.", ["economy", "trade"]),
    ("消費", "consumption", "若者の車離れが進み、自動車の国内消費が年々減少している。", "With young people increasingly moving away from owning cars, domestic automobile consumption is declining year by year.", ["economy", "society"]),
    ("物価", "prices", "原油価格の高騰により、あらゆる商品の物価が上昇し続けている。", "Due to the soaring crude oil prices, the prices of all kinds of goods continue to rise.", ["economy", "society"]),
    ("インフレ", "inflation", "急激なインフレにより、紙幣の価値が下がり人々の生活は苦しくなった。", "Due to rapid inflation, the value of paper money dropped, making people's lives difficult.", ["economy", "society"]),

    ("温暖化", "global warming", "地球温暖化の影響で、海面の上昇や異常気象が世界各地で起きている。", "Due to global warming, rising sea levels and extreme weather are occurring worldwide.", ["environment", "science"]),
    ("汚染", "pollution", "工場から排出された有害物質により、川の水が深刻に汚染された。", "The river water was severely polluted by harmful substances discharged from the factory.", ["environment", "society"]),
    ("資源", "resources", "限りある地球の資源を大切にし、次世代に残していく責任がある。", "We have a responsibility to cherish the earth's limited resources and preserve them for the next generation.", ["environment", "society"]),
    ("排出", "emission", "政府は、温室効果ガスの排出を大幅に削減する新たな目標を設定した。", "The government set a new target to significantly reduce greenhouse gas emissions.", ["environment", "policy"]),
    ("エコ", "eco, environmentally friendly", "最近では、マイボトルを持ち歩くなど、エコなライフスタイルが定着してきた。", "Recently, eco-friendly lifestyles, such as carrying a reusable water bottle, have become established.", ["environment", "lifestyle"]),
    ("リサイクル", "recycle", "使い終わったペットボトルは、洗ってリサイクルに出すようにしている。", "I make sure to wash and put out used plastic bottles for recycling.", ["environment", "lifestyle"]),
    ("砂漠化", "desertification", "過度な放牧や森林伐採が原因で、深刻な砂漠化が進行している地域がある。", "Severe desertification is progressing in some regions due to excessive grazing and deforestation.", ["environment", "geography"]),
    ("生態系", "ecosystem", "外来種の侵入により、その地域の豊かな生態系が破壊される恐れがある。", "The invasion of alien species threatens to destroy the region's rich ecosystem.", ["environment", "science"]),
    ("保護", "protection", "絶滅の危機に瀕している野生動物を保護するため、特別な法律が制定された。", "Special laws were enacted to protect endangered wild animals.", ["environment", "law"]),
    ("破壊", "destruction", "利益を優先するあまり、取り返しのつかない環境破壊が進んでしまった。", "In prioritizing profit, irreversible environmental destruction has advanced.", ["environment", "society"]),
    ("節約", "saving, conservation", "地球環境を守るためにも、日頃から水や電気の節約を心がけたい。", "To protect the global environment, I want to keep in mind saving water and electricity on a daily basis.", ["environment", "lifestyle"]),
    ("消費量", "amount of consumption", "先進国におけるエネルギーの消費量は、発展途上国に比べて圧倒的に多い。", "The amount of energy consumption in developed countries is overwhelmingly larger than in developing countries.", ["environment", "economy"]),
    ("廃棄", "disposal", "大量の食品が毎日廃棄されている現状は、大きな社会問題となっている。", "The current situation where massive amounts of food are disposed of daily has become a major social issue.", ["environment", "society"]),
    ("ゴミ処理", "garbage disposal", "人口の増加に伴い、都市部でのゴミ処理能力が限界に近づいている。", "With the population increase, garbage disposal capacity in urban areas is approaching its limit.", ["environment", "society"]),
    ("騒音", "noise pollution", "空港の近くに住む人々は、飛行機の離着陸に伴う騒音に悩まされている。", "People living near the airport are troubled by the noise pollution associated with planes taking off and landing.", ["environment", "society"]),
    ("自然環境", "natural environment", "開発が進む一方で、いかにして自然環境を保全するかが今後の課題だ。", "While development progresses, how to conserve the natural environment is a future challenge.", ["environment", "society"]),
    ("気候変動", "climate change", "急激な気候変動は、農業や生態系に計り知れない影響を与えると懸念されている。", "There are concerns that rapid climate change will have immeasurable impacts on agriculture and ecosystems.", ["environment", "science"]),
    ("温室効果ガス", "greenhouse gas", "世界各国が協力して、温室効果ガスの削減に向けた取り組みを進めている。", "Countries around the world are cooperating to advance efforts to reduce greenhouse gases.", ["environment", "policy"]),
    ("オゾン層", "ozone layer", "オゾン層が破壊されると、有害な紫外線が地上に多く降り注ぐことになる。", "If the ozone layer is destroyed, an increased amount of harmful ultraviolet rays will pour down on the ground.", ["environment", "science"]),
    ("紫外線", "ultraviolet rays", "夏の強い紫外線から肌を守るため、外出時は必ず日焼け止めを塗っている。", "To protect my skin from strong summer ultraviolet rays, I always apply sunscreen when going out.", ["health", "environment"]),
    ("酸性雨", "acid rain", "工場からの排気ガスが原因で酸性雨が降り、森林が立ち枯れる被害が出た。", "Acid rain caused by factory exhaust emissions fell, resulting in damage where forests withered away.", ["environment", "science"]),
    ("有害", "harmful", "この塗料には人体に有害な化学物質が含まれているため、取り扱いに注意が必要だ。", "Because this paint contains chemical substances harmful to the human body, careful handling is required.", ["environment", "health"]),
    ("放射能", "radioactivity", "原子力発電所の事故により、周囲に放射能が漏れ出すという最悪の事態が発生した。", "The worst-case scenario occurred where radioactivity leaked into the surroundings due to the nuclear power plant accident.", ["environment", "disaster"]),
    ("再利用", "reuse", "不要になった衣類を捨てるのではなく、布巾などに再利用している。", "Instead of throwing away unneeded clothing, we reuse it for things like dishcloths.", ["environment", "lifestyle"]),
    ("分別", "separation", "ゴミの分別ルールが細かくなり、最初は少し戸惑う住民も多かった。", "As the rules for garbage separation became detailed, many residents were initially a bit confused.", ["environment", "daily life"]),
    ("環境問題", "environmental issues", "環境問題は一国だけで解決できるものではなく、国際的な協力が不可欠だ。", "Environmental issues cannot be solved by a single country alone; international cooperation is indispensable.", ["environment", "policy"]),
    ("エコバッグ", "reusable bag", "レジ袋の有料化に伴い、買い物には必ずエコバッグを持参するようになった。", "With plastic bags no longer being free, I have started always bringing a reusable bag when shopping.", ["environment", "daily life"]),
    ("森林伐採", "deforestation", "熱帯雨林の急速な森林伐採は、多くの動植物から住処を奪っている。", "The rapid deforestation of tropical rainforests is depriving many animals and plants of their habitats.", ["environment", "science"]),
    ("絶滅", "extinction", "かつて地球を支配していた恐竜は、環境の激変によって絶滅したと考えられている。", "Dinosaurs, which once dominated the earth, are believed to have faced extinction due to a drastic environmental change.", ["environment", "science"]),
    ("天然資源", "natural resources", "自国に天然資源を持たないこの国は、輸入への依存度が高い。", "This country, which lacks natural resources of its own, has a high degree of dependence on imports.", ["environment", "economy"]),

    ("画面", "screen", "スマートフォンの画面を見続けたせいで、目がすっかり疲れてしまった。", "My eyes are completely exhausted from constantly staring at my smartphone screen.", ["technology", "daily life"]),
    ("装置", "device, equipment", "この工場には、製品の欠陥を自動で検知する最新の装置が導入されている。", "This factory has introduced the latest equipment that automatically detects product defects.", ["technology", "business"]),
    ("開発", "development", "その企業は、誰でも簡単に使える新しいアプリの開発に力を入れている。", "That company is focusing its efforts on the development of a new app that anyone can easily use.", ["technology", "business"]),
    ("検索", "search", "分からない言葉があったら、すぐにインターネットで検索するようにしている。", "If there's a word I don't know, I make it a habit to immediately search for it on the internet.", ["technology", "daily life"]),
    ("接続", "connection", "地下鉄の中ではインターネットの接続が不安定になりがちだ。", "Internet connection tends to become unstable inside the subway.", ["technology", "daily life"]),
    ("パスワード", "password", "セキュリティ上の理由から、パスワードは定期的に変更することが推奨されている。", "For security reasons, it is recommended to change your password regularly.", ["technology", "security"]),
    ("ログイン", "login", "会員専用のページにアクセスするには、まずログインIDを入力してください。", "To access the members-only page, please enter your login ID first.", ["technology", "internet"]),
    ("インストール", "installation", "新しいソフトウェアをパソコンにインストールするのに、かなり時間がかかった。", "It took quite a while to install the new software on the computer.", ["technology", "computing"]),
    ("ダウンロード", "download", "大容量の動画ファイルをダウンロードする際は、Wi-Fi環境を利用した方がいい。", "When downloading large video files, it's better to use a Wi-Fi environment.", ["technology", "internet"]),
    ("アップロード", "upload", "旅行先で撮った写真をSNSにアップロードして、友人たちと共有した。", "I uploaded the photos I took on my trip to social media and shared them with my friends.", ["technology", "internet"]),
    ("デジタル", "digital", "カメラがデジタル化されたことで、写真の現像という作業は過去のものになった。", "With cameras becoming digital, the process of developing photos has become a thing of the past.", ["technology", "society"]),
    ("アナログ", "analog", "すべてがデジタル化される現代だからこそ、アナログな手紙の温かさが心に響く。", "Precisely because everything is digitized today, the warmth of an analog handwritten letter touches the heart.", ["technology", "lifestyle"]),
    ("バッテリー", "battery", "長時間の外出時には、スマートフォンのモバイルバッテリーを持ち歩くようにしている。", "When going out for a long time, I make sure to carry a mobile battery for my smartphone.", ["technology", "daily life"]),
    ("充電", "charging", "寝る前にスマートフォンを充電器に繋いでおくのを忘れてしまった。", "I forgot to connect my smartphone to the charger before going to sleep.", ["technology", "daily life"]),
    ("履歴", "history, record", "ブラウザの閲覧履歴を削除して、プライバシーを保護した。", "I deleted my browser's viewing history to protect my privacy.", ["technology", "security"]),
    ("編集", "editing", "撮影した映像に効果音やテロップを追加して、見やすく編集した。", "I added sound effects and text to the filmed footage, editing it to make it easier to watch.", ["technology", "media"]),
    ("削除", "deletion", "誤って重要なデータを削除してしまい、上司に厳しく叱られた。", "I mistakenly deleted important data and was strictly scolded by my boss.", ["technology", "business"]),
    ("保存", "save, storage", "作成した文書は、こまめに保存しないとデータが消える危険がある。", "If you don't save the document you're creating frequently, there's a risk of losing the data.", ["technology", "computing"]),
    ("コピー", "copy", "会議の資料を参加者の人数分コピーして、机の上に配っておいてください。", "Please make copies of the meeting materials for the number of participants and distribute them on the desks.", ["technology", "business"]),
    ("貼り付け", "paste", "別の文書から文章をコピーして、こちらの資料に貼り付けた。", "I copied text from another document and pasted it into these materials.", ["technology", "computing"]),
    ("添付", "attachment", "先ほどのメールに企画書のPDFファイルを添付しましたので、ご確認ください。", "I attached the project proposal PDF file to the previous email, so please check it.", ["technology", "business"]),
    ("返信", "reply", "取引先からの重要なメールには、内容を確認してすぐに返信しなければならない。", "You must review the content and reply immediately to important emails from business partners.", ["technology", "business"]),
    ("転送", "forward", "担当者が不在だったため、送られてきたメールを本人のスマートフォンに転送した。", "Since the person in charge was absent, I forwarded the received email to his smartphone.", ["technology", "business"]),
    ("通知", "notification", "スマートフォンの通知音が鳴り止まず、仕事に集中できなかった。", "My smartphone's notification sound wouldn't stop ringing, and I couldn't concentrate on my work.", ["technology", "daily life"]),
    ("設定", "settings", "新しいパソコンを購入したので、初期設定をするのに一日がかりだった。", "Because I bought a new computer, it took me all day to do the initial settings.", ["technology", "computing"]),
    ("アカウント", "account", "SNSのアカウントが何者かに乗っ取られ、迷惑なメッセージが送信されてしまった。", "My social media account was hijacked by someone, and spam messages were sent out.", ["technology", "security"]),
    ("ネット", "internet", "わからないことがあれば、すぐにネットで調べるのが現代人の習慣だ。", "It is a habit of modern people to immediately look things up on the internet if there is something they don't know.", ["technology", "society"]),
    ("電波", "radio wave", "山奥のキャンプ場に入るとスマートフォンの電波が全く届かなくなった。", "Once we entered the campsite deep in the mountains, smartphone radio waves couldn't reach us at all.", ["technology", "travel"]),
    ("通信", "communication, transmission", "災害時に通信網が遮断されると、救助活動に大きな支障が出る。", "If communication networks are cut off during a disaster, it causes major hindrances to rescue operations.", ["technology", "disaster"]),
    ("人工知能", "artificial intelligence", "医療の現場でも、人工知能による画像の解析や診断の支援が始まっている。", "Even in the medical field, image analysis and diagnostic support by artificial intelligence have begun.", ["technology", "science"]),

    ("寿命", "lifespan", "医療技術の進歩により、人間の平均寿命は過去百年で飛躍的に伸びた。", "Thanks to advances in medical technology, the average human lifespan has increased dramatically over the past hundred years.", ["health", "society"]),
    ("高齢化", "aging population", "急速な高齢化に伴い、介護施設の不足が深刻な社会問題となっている。", "With the rapidly aging population, the shortage of nursing care facilities has become a serious social issue.", ["society", "health"]),
    ("福祉", "welfare", "北欧の国々は、税金が高い代わりに充実した社会福祉制度が整っている。", "Although taxes are high, Nordic countries have well-established social welfare systems in return.", ["society", "policy"]),
    ("症状", "symptom", "熱はないものの、咳と喉の痛みが続くという風邪の症状に悩まされている。", "Though I have no fever, I am bothered by cold symptoms of a persistent cough and sore throat.", ["health", "medicine"]),
    ("睡眠", "sleep", "質の高い睡眠をとることは、日々の疲労を回復し健康を保つために不可欠だ。", "Getting high-quality sleep is essential for recovering from daily fatigue and maintaining health.", ["health", "lifestyle"]),
    ("疲労", "fatigue", "長時間の運転による疲労が蓄積し、彼はハンドルを握ったまま眠ってしまった。", "Fatigue from driving for long hours accumulated, and he fell asleep holding the steering wheel.", ["health", "accident"]),
    ("栄養", "nutrition", "成長期の子供には、バランスの取れた栄養のある食事が特に重要である。", "For children in their growing period, well-balanced and nutritious meals are particularly important.", ["health", "lifestyle"]),
    ("手術", "surgery", "最新のロボット技術を導入したことで、より安全で精密な手術が可能になった。", "The introduction of the latest robot technology has made safer and more precise surgeries possible.", ["health", "medicine"]),
    ("診断", "diagnosis", "複数の医師から話を聞き、最終的に癌ではないという正確な診断を受けた。", "After consulting multiple doctors, I eventually received an accurate diagnosis that it was not cancer.", ["health", "medicine"]),
    ("治療", "treatment", "この新しい薬は、これまで治癒が難しいとされていた病気の治療に期待されている。", "This new medicine is expected to be used in the treatment of diseases that were previously considered difficult to cure.", ["health", "medicine"]),
    ("予防", "prevention", "感染症の予防には、こまめな手洗いと適切なマスクの着用が最も効果的だ。", "For the prevention of infectious diseases, frequent hand washing and appropriate mask-wearing are most effective.", ["health", "medicine"]),
    ("ワクチン", "vaccine", "冬が本格化する前に、多くの人がインフルエンザのワクチンを接種しに病院を訪れる。", "Before winter sets in properly, many people visit the hospital to get vaccinated against influenza.", ["health", "medicine"]),
    ("感染", "infection", "ウイルスは飛沫を通じて空気中に広がり、周囲の人々へ容易に感染していく。", "The virus spreads into the air through droplets, easily infecting people nearby.", ["health", "medicine"]),
    ("対策", "measure, countermeasure", "政府は、深刻化する少子化を食い止めるための具体的な対策を急いでいる。", "The government is hurrying concrete measures to halt the worsening declining birthrate.", ["society", "policy"]),
    ("少子化", "declining birthrate", "少子化によって将来の労働力不足が懸念され、外国人労働者の受け入れが議論されている。", "Due to the declining birthrate, there are concerns about a future labor shortage, and the acceptance of foreign workers is being discussed.", ["society", "economy"]),
    ("差別", "discrimination", "性別や人種に基づくあらゆる差別は、法によって厳しく禁じられている。", "All forms of discrimination based on gender or race are strictly prohibited by law.", ["society", "law"]),
    ("平等", "equality", "民主主義社会においては、すべての市民が法の下に平等でなければならない。", "In a democratic society, all citizens must be equal under the law.", ["society", "politics"]),
    ("権利", "rights", "教育を受ける権利は、憲法によって保障された基本的な人権の一つである。", "The right to receive an education is one of the fundamental human rights guaranteed by the constitution.", ["society", "law"]),
    ("義務", "duty, obligation", "国民には、国を支えるための税金を納めるという重要な義務がある。", "Citizens have an important duty to pay taxes to support the country.", ["society", "law"]),
    ("犯罪", "crime", "監視カメラの設置が増えたことで、街中での凶悪な犯罪の発生件数は減少傾向にある。", "With the increased installation of surveillance cameras, the occurrence of vicious crimes in the city is on a declining trend.", ["society", "law"]),
    ("逮捕", "arrest", "長期間の捜査の末、警察はついに連続強盗事件の容疑者を逮捕した。", "After a long-term investigation, the police finally arrested the suspect in the serial robbery case.", ["society", "law"]),
    ("裁判", "trial", "その複雑な事件の裁判は数年に及び、関係者は長期間拘束されることになった。", "The trial for that complex case spanned several years, leaving those involved tied up for a long period.", ["society", "law"]),
    ("法律", "law", "社会の急激な変化に対応するため、既存の法律を改正する動きが活発化している。", "To respond to rapid changes in society, movements to revise existing laws are becoming active.", ["society", "law"]),
    ("規則", "rule, regulation", "寮の厳しい規則を破った学生は、退寮処分という重いペナルティを受ける。", "Students who break the strict dorm regulations face the heavy penalty of eviction.", ["society", "education"]),
    ("制度", "system, institution", "新しい教育制度の導入により、学校現場では大きな混乱が生じている。", "The introduction of the new educational system is causing major confusion on school grounds.", ["society", "education"]),
    ("保険", "insurance", "万が一の病気や怪我に備えて、社会人になったのを機に民間の医療保険に加入した。", "To prepare for unexpected illness or injury, I enrolled in private medical insurance upon entering the workforce.", ["health", "economy"]),
    ("年金", "pension", "少子高齢化の影響で、将来自分が十分な年金を受け取れるのか不安に感じる若者が多い。", "Due to the aging population with a declining birthrate, many young people feel anxious about whether they will receive a sufficient pension in the future.", ["society", "economy"]),
    ("税務署", "tax office", "個人事業主は、毎年決められた時期に税務署へ確定申告の書類を提出しなければならない。", "Sole proprietors must submit their final tax return documents to the tax office at a designated time every year.", ["economy", "society"]),
    ("労働", "labor", "過酷な労働環境を改善するため、労働組合が会社側と激しく交渉している。", "To improve harsh labor environments, the labor union is negotiating fiercely with the company.", ["society", "business"]),
    ("ストレス", "stress", "現代人は複雑な人間関係や仕事の重圧から、常に多くのストレスを抱えて生きている。", "Modern people live constantly bearing a lot of stress from complex human relationships and heavy workloads.", ["health", "society"]),

    ("衝突", "collision", "交差点でトラックと乗用車が正面から衝突する大きな事故が発生した。", "A major accident occurred where a truck and a passenger car collided head-on at an intersection.", ["accident", "transportation"]),
    ("欠航", "flight cancellation", "猛烈な台風の接近により、本日の国内線はすべて欠航となることが決定した。", "Due to the approach of a fierce typhoon, it was decided that all domestic flights today will be canceled.", ["travel", "disaster"]),
    ("渋滞", "traffic jam", "連休の初日ということもあり、高速道路は数十キロにわたる深刻な渋滞に見舞われている。", "Partly because it's the first day of the long weekend, the expressway is experiencing a severe traffic jam stretching for tens of kilometers.", ["travel", "transportation"]),
    ("被害", "damage, harm", "記録的な大雨による土砂崩れで、多くの家屋が押し流されるという甚大な被害が出た。", "A landslide caused by record heavy rain resulted in immense damage, with many houses being swept away.", ["disaster", "society"]),
    ("復旧", "restoration, recovery", "地震で寸断された鉄道網の復旧には、少なくとも数ヶ月を要する見通しだ。", "It is estimated that the restoration of the railway network severed by the earthquake will take at least several months.", ["disaster", "infrastructure"]),
    ("事故", "accident", "彼は旅行先で不注意から交通事故に巻き込まれ、重傷を負ってしまった。", "He was involved in a traffic accident due to carelessness while traveling and suffered serious injuries.", ["accident", "travel"]),
    ("故障", "breakdown, failure", "大事なプレゼンの直前にプロジェクターが故障し、担当者はパニックに陥った。", "The projector broke down right before an important presentation, sending the person in charge into a panic.", ["technology", "business"]),
    ("救助", "rescue", "山で遭難した登山者を捜索するため、ヘリコプターによる懸命な救助活動が行われた。", "Desperate rescue operations by helicopter were carried out to search for the climbers stranded in the mountains.", ["disaster", "accident"]),
    ("避難", "evacuation", "津波警報が発令された直後、住民たちは高台にある安全な場所へと速やかに避難した。", "Immediately after the tsunami warning was issued, residents swiftly evacuated to a safe place on high ground.", ["disaster", "society"]),
    ("停電", "power outage", "落雷が原因で大規模な停電が発生し、街中が真っ暗闇に包まれた。", "A massive power outage occurred due to a lightning strike, enveloping the entire city in pitch darkness.", ["disaster", "infrastructure"]),
    ("断水", "water outage", "水道管の破裂により広い地域で断水が続き、人々の生活に深刻な影響が出ている。", "Due to a burst water pipe, the water outage continues over a wide area, seriously affecting people's lives.", ["disaster", "infrastructure"]),
    ("地震", "earthquake", "深夜に発生した強い地震で目を覚まし、恐怖でしばらく動くことができなかった。", "Woken up by a strong earthquake that occurred late at night, I couldn't move for a while out of fear.", ["disaster", "nature"]),
    ("津波", "tsunami", "地震の後に巨大な津波が沿岸部を襲い、多くの街が壊滅的な打撃を受けた。", "Following the earthquake, a massive tsunami struck the coastal areas, dealing a devastating blow to many towns.", ["disaster", "nature"]),
    ("洪水", "flood", "何日も降り続いた雨のせいで川が氾濫し、周囲の住宅街が洪水に飲み込まれた。", "The river overflowed due to rain that continued to fall for days, and the surrounding residential areas were swallowed by a flood.", ["disaster", "nature"]),
    ("台風", "typhoon", "大型の台風が上陸する恐れがあるため、窓ガラスを補強するなどの対策が必要だ。", "Because there is a fear that a large typhoon will make landfall, measures such as reinforcing window glass are necessary.", ["disaster", "nature"]),
    ("火災", "fire", "乾燥した空気が原因で山林火災が発生し、消防隊が懸命な消火活動に当たっている。", "A forest fire broke out due to the dry air, and the fire brigade is engaged in desperate firefighting efforts.", ["disaster", "accident"]),
    ("発生", "occurrence", "高速道路上で多重事故が発生したため、一部の区間が完全に通行止めとなっている。", "Because a multi-vehicle accident occurred on the expressway, a section of the road is completely closed to traffic.", ["accident", "transportation"]),
    ("防止", "prevention", "駅のホームでの転落事故を防止するため、安全柵の設置が急ピッチで進められている。", "To prevent falling accidents on station platforms, the installation of safety fences is proceeding at a rapid pace.", ["accident", "infrastructure"]),
    ("警戒", "warning, caution", "気象庁は、大雨による土砂災害や河川の増水に対して最大級の警戒を呼びかけている。", "The Meteorological Agency is calling for maximum caution against landslides and rising river levels caused by heavy rain.", ["disaster", "nature"]),
    ("運休", "suspension of service", "大雪の影響により、本日の新幹線は終日運休となることが発表された。", "It was announced that today's Shinkansen services will be suspended all day due to the impact of heavy snow.", ["travel", "disaster"]),
    ("延期", "postponement", "悪天候が予想されるため、楽しみにしていた野外フェスティバルは来週に延期された。", "Because bad weather is expected, the outdoor festival we were looking forward to was postponed to next week.", ["event", "weather"]),
    ("変更", "change", "飛行機の出発時刻が急に変更されたため、空港で慌てて搭乗手続きをやり直した。", "Because the flight's departure time was suddenly changed, I rushed to redo the boarding procedures at the airport.", ["travel", "transportation"]),
    ("払い戻し", "refund", "コンサートが中止になったため、チケット代金の払い戻し手続きを窓口で行った。", "Since the concert was canceled, I went through the procedures for a ticket refund at the counter.", ["travel", "event"]),
    ("迷子", "lost child/person", "混雑した遊園地で親とはぐれてしまい、一時的に迷子になって泣きそうだった。", "I got separated from my parents at the crowded amusement park and was close to tears after temporarily becoming a lost child.", ["travel", "daily life"]),
    ("落とし物", "lost property", "電車の中で見つけた財布を、駅の係員に落とし物として届け出た。", "I turned in a wallet I found on the train to the station attendant as lost property.", ["travel", "daily life"]),
    ("盗難", "theft", "海外旅行中にパスポートや貴重品の入ったバッグを盗難に遭い、警察沙汰になった。", "While traveling overseas, my bag containing my passport and valuables was stolen, leading to police involvement.", ["travel", "crime"]),
    ("詐欺", "fraud", "高齢者を狙った悪質な電話詐欺が多発しており、警察が注意を呼びかけている。", "Malicious telephone fraud targeting the elderly is occurring frequently, and the police are calling for caution.", ["crime", "society"]),
    ("危険", "danger", "この先は崖崩れの危険があるため、立ち入りが厳しく制限されている。", "Because there is a danger of landslides ahead, entry is strictly restricted.", ["disaster", "nature"]),
    ("無事", "safety, unharmed", "嵐の中で遭難した船の乗組員が、全員無事に救助されたというニュースが流れた。", "News broke that all the crew members of the ship stranded in the storm were rescued safely.", ["accident", "disaster"]),
    ("被災者", "disaster victim", "全国から集まったボランティアが、被災者に温かい食事や衣服を提供している。", "Volunteers gathered from all over the country are providing warm meals and clothing to the disaster victims.", ["disaster", "society"])
]

for i, (front, back, jp, en, tags) in enumerate(items, 1):
    shard["cards"].append(create_card(i, front, back, jp, en, tags))

out_dir = 'c:/Users/songo/kanji-srs/data/curated-packs/en/intake/n2'
os.makedirs(out_dir, exist_ok=True)
out_file = os.path.join(out_dir, 'vocab_d_media_economy_environment_180.json')

with open(out_file, 'w', encoding='utf-8') as f:
    json.dump(shard, f, ensure_ascii=False, indent=2)

print(f"Generated {len(shard['cards'])} cards in {out_file}")
