kanji_2 = [
    ("投", "throw", "ボールを遠くまで投げる練習をしている。", "I am practicing throwing the ball far."),
    ("示", "show, indicate", "先生が黒板に問題の答えを示した。", "The teacher showed the answer to the problem on the blackboard."),
    ("変", "change, strange", "髪型を変えたら、友達に驚かれた。", "When I changed my hairstyle, my friends were surprised."),
    ("打", "hit, strike", "パソコンで文章を打つのに慣れてきた。", "I have gotten used to typing text on a computer."),
    ("直", "straight, fix", "壊れた自転車を自分で直してみた。", "I tried to fix the broken bicycle myself."),
    ("両", "both", "両親の結婚記念日にプレゼントを贈った。", "I gave my parents a present on their wedding anniversary."),
    ("式", "ceremony, style", "明日は大学の卒業式に参加します。", "I will participate in the university graduation ceremony tomorrow."),
    ("確", "certain, sure", "出発の時間をもう一度確認してください。", "Please confirm the departure time once more."),
    ("果", "fruit, result", "毎日の練習の結果、大会で優勝できた。", "As a result of daily practice, I was able to win the tournament."),
    ("容", "contain, form", "このカバンは容量が大きくて便利だ。", "This bag has a large capacity and is convenient."),
    ("必", "certain, necessary", "外国に行くときはパスポートが必ず必要だ。", "A passport is absolutely necessary when going abroad."),
    ("演", "perform, play", "有名な俳優が舞台で素晴らしい演技をした。", "A famous actor gave a wonderful performance on stage."),
    ("歳", "year-end, age", "今年で二十歳になり、お酒が飲めるようになった。", "I turned twenty this year and can now drink alcohol."),
    ("争", "contend, dispute", "兄弟でテレビのチャンネルを争うのはやめなさい。", "Stop fighting over the TV channel with your brother."),
    ("談", "discuss, talk", "先生と進路について面談をした。", "I had an interview with the teacher about my future path."),
    ("能", "ability", "彼女は語学の才能があり、3か国語を話せる。", "She has a talent for languages and can speak three languages."),
    ("位", "rank, position", "テストの成績でクラスの1位になった。", "I became first in the class in the test results."),
    ("置", "put, place", "机の上に辞書が置いてあります。", "There is a dictionary placed on the desk."),
    ("流", "stream, flow", "川の水が静かに流れている。", "The river water is flowing quietly."),
    ("格", "status, capacity", "そのホテルは格式が高く、とても高級だ。", "That hotel has a high status and is very luxurious."),
    ("疑", "doubt", "彼の言っていることが本当かどうか疑わしい。", "It is doubtful whether what he is saying is true or not."),
    ("過", "overdo, pass", "楽しい時間はあっという間に過ぎてしまう。", "Fun times pass by in the blink of an eye."),
    ("局", "bureau, board", "荷物を送るために郵便局へ行った。", "I went to the post office to send a package."),
    ("放", "set free, release", "テレビで面白い番組が放送されている。", "An interesting program is being broadcasted on TV."),
    ("常", "usual, normal", "日常生活の中で、運動する時間を作りたい。", "I want to make time to exercise in my daily life."),
    ("状", "conditions, form", "今の健康状態は非常に良いです。", "My current state of health is very good."),
    ("球", "ball, sphere", "休日は公園で野球をして遊んでいる。", "I play baseball in the park on my days off."),
    ("職", "post, employment", "新しい職場の人たちはみんな親切だ。", "Everyone at the new workplace is kind."),
    ("与", "give", "子供たちに夢を与えるような仕事がしたい。", "I want to do a job that gives dreams to children."),
    ("供", "offer, provide", "このレストランは美味しい料理を提供している。", "This restaurant provides delicious food."),
    ("役", "duty, role", "彼女は映画で重要な役を演じた。", "She played an important role in the movie."),
    ("構", "posture, build", "この建物の構造はとても複雑だ。", "The structure of this building is very complex."),
    ("割", "proportion, divide", "ケーキを3つに割って、みんなで食べましょう。", "Let's divide the cake into three and eat it together."),
    ("費", "expense", "今月は生活費を節約しなければならない。", "I have to save on living expenses this month."),
    ("付", "adhere, attach", "書類に写真と履歴書を付けて送った。", "I sent the documents with a photo and a resume attached."),
    ("由", "wherefore, reason", "彼が遅刻した理由を聞いて驚いた。", "I was surprised to hear the reason why he was late."),
    ("説", "theory, explain", "社長が新しいプロジェクトについて説明した。", "The company president explained the new project."),
    ("難", "difficult", "この本は内容が難しくて、なかなか進まない。", "The contents of this book are difficult, so I am not making much progress."),
    ("優", "superior, gentle", "彼女はとても優しくて、みんなから好かれている。", "She is very gentle and liked by everyone."),
    ("夫", "husband", "私の夫は料理を作るのが上手です。", "My husband is good at cooking."),
    ("収", "income, obtain", "今年の会社の収入は去年よりも増えた。", "The company's income this year increased compared to last year."),
    ("断", "sever, decide", "忙しいので、パーティーの誘いを断った。", "I refused the invitation to the party because I am busy."),
    ("石", "stone", "道に落ちている石につまずいて転んだ。", "I tripped over a stone on the road and fell."),
    ("違", "difference, differ", "私の意見は彼の意見と少し違います。", "My opinion differs a little from his."),
    ("消", "extinguish, erase", "部屋を出る時は、必ず電気を消してください。", "When you leave the room, please be sure to turn off the lights."),
    ("神", "gods, mind", "試験に合格するように、神社で神様にお願いした。", "I prayed to the gods at the shrine so that I would pass the exam."),
    ("番", "turn, number", "テレビのチャンネルを8番に変えてください。", "Please change the TV channel to number 8."),
    ("規", "standard, measure", "会社の規則を守ることは社会人として当然だ。", "Following company rules is natural as a working adult."),
    ("術", "art, technique", "最新の技術を使って、新しい製品を開発した。", "We developed a new product using the latest technology."),
    ("備", "equip, prepare", "地震に備えて、水や食料を準備しておく。", "I prepare water and food in preparation for an earthquake."),
    ("宅", "home, house", "昨日の夜は自宅でのんびり映画を見ていた。", "I was relaxing and watching a movie at home last night."),
    ("害", "harm, injury", "台風で農作物に大きな被害が出た。", "The typhoon caused great damage to the crops."),
    ("配", "distribute", "朝、新聞を配達するアルバイトをしている。", "I have a part-time job delivering newspapers in the morning."),
    ("警", "admonish, warn", "交差点に立って、警察官が交通整理をしている。", "A police officer is standing at the intersection directing traffic."),
    ("育", "bring up, raise", "田舎で野菜を育てながら静かに暮らしたい。", "I want to live quietly in the countryside while growing vegetables."),
    ("席", "seat", "電車の中で、お年寄りに席を譲った。", "I gave up my seat to an elderly person on the train."),
    ("訪", "call on, visit", "夏休みに京都の古いお寺を訪問する予定だ。", "I plan to visit an old temple in Kyoto during the summer vacation."),
    ("乗", "ride, board", "毎朝、満員の通勤電車に乗るのは大変だ。", "Riding a crowded commuter train every morning is tough."),
    ("残", "remainder, left over", "冷蔵庫に残っている野菜でスープを作った。", "I made soup with the vegetables left in the refrigerator."),
    ("想", "concept, think", "将来の自分の姿を想像してみる。", "I try to imagine myself in the future."),
    ("声", "voice", "彼の声はとてもきれいで、歌が上手だ。", "His voice is very beautiful and he is good at singing."),
    ("念", "thought, desire", "残念ながら、明日の試合は雨で中止になった。", "Unfortunately, tomorrow's match was canceled due to rain."),
    ("助", "help", "困っているおばあさんを助けてあげた。", "I helped an elderly woman who was in trouble."),
    ("労", "labor, toil", "長時間労働が問題になっている。", "Long working hours have become a problem."),
    ("例", "example", "例えば、どんな音楽が好きですか。", "For example, what kind of music do you like?"),
    ("然", "sort of thing, so", "自然の豊かな場所でキャンプをするのが好きだ。", "I like camping in places rich in nature."),
    ("限", "limit, restrict", "チケットの数には限りがあります。", "There is a limit to the number of tickets."),
    ("追", "chase", "犬がボールを追いかけて走っていった。", "The dog ran chasing after the ball."),
    ("商", "make a deal", "商店街で新鮮な魚を買って帰った。", "I bought fresh fish at the shopping street and went home."),
    ("葉", "leaf", "秋になると、木々の葉が赤や黄色に変わる。", "In autumn, the leaves of trees turn red and yellow."),
    ("伝", "transmit, tell", "このメッセージを彼に伝えてもらえませんか。", "Could you pass this message on to him?"),
    ("働", "work", "彼は毎日夜遅くまで一生懸命働いている。", "He works hard until late every night."),
    ("形", "shape", "このケーキは星の形をしていて可愛い。", "This cake is cute, shaped like a star."),
    ("景", "scenery", "ホテルの窓から見える景色がすばらしい。", "The scenery visible from the hotel window is wonderful."),
    ("落", "fall, drop", "ポケットから財布を落としてしまった。", "I dropped my wallet from my pocket."),
    ("好", "fond, pleasing", "休日は好きな本を読んでリラックスする。", "I relax by reading my favorite books on holidays."),
    ("退", "retreat", "病気のために、大学を退学することになった。", "Due to illness, I had to drop out of the university."),
    ("頭", "head", "考えすぎて頭が痛くなってしまった。", "My head started hurting from thinking too much."),
    ("負", "defeat, negative", "今日の試合は強豪チームに負けてしまった。", "We lost today's match to a strong team."),
    ("渡", "transit, cross", "この道をまっすぐ行って、橋を渡ってください。", "Go straight down this road and cross the bridge."),
    ("建", "build", "新しいマンションが駅の近くに建設されている。", "A new apartment building is being constructed near the station."),
    ("終", "end, finish", "夏休みも明日で終わりだ。", "Summer vacation ends tomorrow as well."),
    ("客", "guest, customer", "このレストランはいつもお客さんでいっぱいだ。", "This restaurant is always full of customers."),
    ("識", "discriminating, know", "日本社会についての知識をもっと深めたい。", "I want to deepen my knowledge of Japanese society."),
    ("呼", "call", "タクシーを呼んで、急いで駅に向かった。", "I called a taxi and hurried to the station."),
    ("飛", "fly", "空を鳥が気持ちよさそうに飛んでいる。", "Birds are flying in the sky looking comfortable."),
    ("越", "surpass, cross", "山を越えると、美しい湖が見えてきた。", "After crossing the mountain, a beautiful lake came into view."),
    ("守", "protect", "家族の笑顔を守るために一生懸命働く。", "I work hard to protect my family's smiles."),
    ("庭", "courtyard, garden", "休日は庭で花を育てて楽しんでいる。", "I enjoy growing flowers in the garden on holidays."),
    ("息", "breath, son", "深呼吸をして、息を整えてから走る。", "I take a deep breath and steady my breathing before running.")
]
