kanji_1 = [
    ("政", "politics, government", "政府の方針が大きく変わるかもしれない。", "The government's policy might change significantly."),
    ("議", "debate, parliament", "次回の会議は明日の午後に予定されている。", "The next meeting is scheduled for tomorrow afternoon."),
    ("民", "people, nation", "多くの市民がそのイベントに参加しました。", "Many citizens participated in the event."),
    ("連", "take along, join", "週末は連休なので、少し遠くまで出かけたい。", "Since it's a long weekend, I want to travel a little far."),
    ("対", "opposite, even", "両親は私の留学に強く反対した。", "My parents strongly opposed my studying abroad."),
    ("部", "section, department", "彼女は営業部の新しい部長として紹介された。", "She was introduced as the new manager of the sales department."),
    ("合", "fit, suit, join", "都合が悪くて、明日の約束はキャンセルさせてください。", "It's inconvenient for me, so please let me cancel tomorrow's appointment."),
    ("市", "market, city", "新しい市長は若い人たちの意見を大切にしている。", "The new mayor values the opinions of young people."),
    ("内", "inside, within", "時間内にレポートを提出しなければならない。", "You must submit the report within the time limit."),
    ("相", "mutual, together", "困ったことがあれば、いつでも私に相談してください。", "If you have any trouble, please consult with me anytime."),
    ("定", "fix, decide", "休日は特に予定がなく、家でのんびり過ごした。", "I had no particular plans for the holiday and spent it relaxing at home."),
    ("回", "times, revolve", "このアンケートは今回で3回目になります。", "This is the third time we are doing this survey."),
    ("選", "choose, elect", "選挙に行くことは、私たちの重要な権利だ。", "Voting in elections is our important right."),
    ("米", "rice, America", "日本人は昔から米を主食としてきた。", "Japanese people have used rice as their staple food since ancient times."),
    ("実", "fruit, reality", "その計画はまだ実現するには早すぎる。", "It is still too early to realize that plan."),
    ("関", "connection, barrier", "人間関係の悩みを抱えている人は多い。", "Many people have worries about human relations."),
    ("決", "decide, agree", "どちらのパソコンを買うか、まだ決心がつかない。", "I haven't made up my mind yet about which computer to buy."),
    ("全", "whole, all", "事故のせいで、電車が完全にストップしてしまった。", "Because of the accident, the train completely stopped."),
    ("表", "surface, express", "彼の表情から、怒っていることがすぐにわかった。", "I could tell right away from his expression that he was angry."),
    ("戦", "war, fight", "チームは最後の試合で激しく戦った。", "The team fought fiercely in the final match."),
    ("経", "pass through", "経済の状況が少しずつ改善しているようだ。", "The economic situation seems to be improving little by little."),
    ("最", "most", "最近、この辺りには新しい店が増えた。", "Recently, the number of new stores in this area has increased."),
    ("現", "present, existing", "現在の状況では、目標を達成するのは難しい。", "In the current situation, it is difficult to achieve the goal."),
    ("調", "investigate", "原因を詳しく調査する必要があります。", "We need to investigate the cause in detail."),
    ("化", "change, -ization", "社会の高齢化は深刻な問題となっている。", "The aging of society has become a serious problem."),
    ("当", "hit, appropriate", "本当に私が宝くじに当たったなんて信じられない。", "I can't believe I actually won the lottery."),
    ("約", "promise, approximately", "約束の時間に10分遅れてしまった。", "I was 10 minutes late for the promised time."),
    ("首", "neck, head", "彼女は首にきれいなスカーフを巻いている。", "She is wearing a pretty scarf around her neck."),
    ("法", "law, method", "この機械の正しい使用法を教えてください。", "Please tell me the correct way to use this machine."),
    ("性", "sex, nature", "男女の性格の違いについて面白い記事を読んだ。", "I read an interesting article about the personality differences between men and women."),
    ("要", "need, important", "この書類を提出する前に、重要な点を確認して。", "Before submitting this document, check the important points."),
    ("制", "system, control", "新しい制服のデザインは学生に人気がある。", "The design of the new school uniform is popular among students."),
    ("治", "govern, cure", "風邪を早く治すために、薬を飲んで寝ます。", "To cure my cold quickly, I will take medicine and sleep."),
    ("務", "task, duties", "私の事務所は駅から歩いて5分のところにあります。", "My office is a five-minute walk from the station."),
    ("成", "turn into, grow", "努力が実り、彼はついに夢を成功させた。", "His efforts paid off, and he finally made his dream a success."),
    ("期", "period, time", "期待していた映画は、思ったよりも面白くなかった。", "The movie I was expecting was not as interesting as I thought."),
    ("取", "take, fetch", "休日はしっかりと睡眠を取るようにしている。", "I make sure to get plenty of sleep on my days off."),
    ("都", "metropolis, capital", "都会での生活は便利だが、物価が高い。", "Life in the city is convenient, but prices are high."),
    ("和", "peace, harmony", "休日は和室でお茶を飲みながらくつろぐのが好きだ。", "On my days off, I like to relax in the Japanese-style room while drinking tea."),
    ("機", "machine, opportunity", "飛行機に乗る前にパスポートを用意してください。", "Please prepare your passport before boarding the airplane."),
    ("平", "flat, ordinary", "平日はいそがしいので、週末に掃除をします。", "I am busy on weekdays, so I clean on weekends."),
    ("加", "add, join", "コーヒーに砂糖とミルクを加えます。", "I add sugar and milk to my coffee."),
    ("受", "receive, catch", "昨日、大学の入学試験を受けました。", "I took the university entrance exam yesterday."),
    ("続", "continue", "雨が3日間も続いていて、外に出られない。", "It has been raining continuously for three days, and I can't go outside."),
    ("進", "advance, progress", "プロジェクトは計画通りに進んでいる。", "The project is progressing according to plan."),
    ("数", "number, count", "会場に来たお客さんの数を数えてください。", "Please count the number of guests who came to the venue."),
    ("記", "write down, record", "毎日の出来事を日記に書いて残している。", "I write down daily events in a diary and keep them."),
    ("初", "first, beginning", "初めての海外旅行で、少し緊張しています。", "I am a little nervous because it is my first trip abroad."),
    ("指", "finger, point", "彼女は薬指にきれいな指輪をしていた。", "She was wearing a beautiful ring on her ring finger."),
    ("権", "authority, right", "誰もが自由に意見を言う権利を持っている。", "Everyone has the right to express their opinions freely."),
    ("支", "support, branch", "大きな木が屋根の重さを支えている。", "A large tree is supporting the weight of the roof."),
    ("産", "produce, birth", "この地域では、おいしいお米がたくさん生産されている。", "A lot of delicious rice is produced in this area."),
    ("点", "point, mark", "テストで100点満点を取ることができた。", "I was able to get a perfect score of 100 on the test."),
    ("報", "report, news", "毎朝、天気予報をチェックしてから家を出る。", "I check the weather forecast every morning before leaving the house."),
    ("済", "finish, settle", "支払いはすでに済ませてあります。", "The payment has already been settled."),
    ("活", "active, lively", "新しい職場でも活発に働きたいと思う。", "I want to work actively at my new workplace as well."),
    ("原", "original, plain", "火事の原因はまだはっきり分かっていない。", "The cause of the fire is not yet clearly known."),
    ("共", "together", "休日は家族と共に過ごす時間が多い。", "I often spend time together with my family on holidays."),
    ("得", "acquire, gain", "この仕事から多くの知識を得ることができた。", "I was able to acquire a lot of knowledge from this job."),
    ("解", "solve, untie", "数学の問題を解くのに時間がかかった。", "It took me a long time to solve the math problem."),
    ("交", "mix, interact", "交差点で信号が変わるのを待っています。", "I am waiting for the traffic light to change at the intersection."),
    ("資", "resources, capital", "この研究には多くの資料が必要です。", "A lot of reference materials are necessary for this research."),
    ("予", "beforehand", "来週の金曜日にホテルの予約を入れた。", "I made a hotel reservation for next Friday."),
    ("向", "face, beyond", "駅に向かって急いで歩き始めた。", "I hurried and started walking toward the station."),
    ("際", "occasion, time", "国際会議で様々な国の代表と話をした。", "I spoke with representatives of various countries at an international conference."),
    ("勝", "win", "今日の試合は私たちが絶対に勝つ。", "We will definitely win today's match."),
    ("面", "face, surface", "この問題には面白い側面があると思う。", "I think this issue has an interesting aspect."),
    ("告", "tell, inform", "駅の広告を見て、新しいスマホを買いたくなった。", "After seeing the advertisement at the station, I wanted to buy a new smartphone."),
    ("反", "anti-, opposite", "彼の行動は社会のルールに違反している。", "His behavior violates the rules of society."),
    ("判", "judge", "その情報が正しいかどうかを判断するのは難しい。", "It is difficult to judge whether that information is correct or not."),
    ("認", "recognize", "彼はついに自分の失敗を認めた。", "He finally admitted his mistake."),
    ("参", "participate", "ボランティア活動に参加して、多くのことを学んだ。", "I participated in volunteer activities and learned a lot."),
    ("利", "profit, advantage", "このカードを利用すると、ポイントが貯まります。", "If you use this card, you will accumulate points."),
    ("組", "assemble", "新しい家具を組み立てるのに半日かかった。", "It took half a day to assemble the new furniture."),
    ("信", "believe, trust", "自分自身を信じて最後までやり抜きたい。", "I want to believe in myself and carry it through to the end."),
    ("在", "exist, locate", "現在、彼はロンドンに留学中です。", "Currently, he is studying abroad in London."),
    ("件", "affair, case", "その事件についての詳しい報道を見た。", "I saw detailed reports about that incident."),
    ("側", "side", "道の反対側に新しいコンビニができた。", "A new convenience store was built on the opposite side of the street."),
    ("任", "responsibility, entrust", "リーダーとしての責任をしっかりと果たしたい。", "I want to firmly fulfill my responsibilities as a leader."),
    ("引", "pull", "ドアを強く引いて開けてください。", "Please pull the door strongly to open it."),
    ("求", "request, demand", "会社は新しい人材を求めている。", "The company is looking for new talent."),
    ("所", "place", "静かで落ち着ける場所を探しています。", "I am looking for a quiet and relaxing place."),
    ("次", "next", "次の電車は何時に出発しますか。", "What time does the next train depart?"),
    ("昨", "yesterday", "昨日は一日中雨が降っていました。", "It rained all day yesterday."),
    ("論", "theory, discuss", "大学で日本の歴史について論文を書いている。", "I am writing a thesis about Japanese history at the university."),
    ("官", "official", "警察官が道を丁寧に教えてくれた。", "The police officer kindly told me the way."),
    ("増", "increase", "最近、体重が増えてしまったので運動を始めた。", "Recently, I've gained weight, so I started exercising."),
    ("係", "person in charge", "その件については、担当の係にご連絡ください。", "Regarding that matter, please contact the person in charge."),
    ("感", "feeling, sense", "彼の歌を聴いて、深く感動しました。", "I was deeply moved listening to his song."),
    ("情", "emotion, condition", "日本の文化についての情報をもっと集めたい。", "I want to gather more information about Japanese culture.")
]
