sentences_1 = [
    ("たとえ雨が降っても、明日の試合は行われます。", "Even if it rains, tomorrow's match will be held."),
    ("日本語の勉強を続ければ続けるほど、面白くなってきます。", "The more I continue studying Japanese, the more interesting it becomes."),
    ("彼は疲れているのか、さっきから何も言わずに座っている。", "Perhaps he is tired; he has been sitting without saying anything for a while."),
    ("このアパートは駅から近いわりに、家賃が安くて便利だ。", "Considering this apartment is close to the station, the rent is cheap and it's convenient."),
    ("風邪をひかないように、毎朝うがいをしています。", "I gargle every morning so that I won't catch a cold."),
    ("あの人は親切なだけでなく、仕事もできるので尊敬されている。", "That person is respected not only because they are kind, but also because they do their job well."),
    ("新しいスマートフォンは、以前のものに比べて画面が大きくて見やすい。", "The new smartphone's screen is bigger and easier to see compared to the previous one."),
    ("もう少しで電車に乗り遅れるところでした。", "I was just about to miss the train."),
    ("休日は掃除したり、洗濯したりして過ごすことが多い。", "On my days off, I often spend time doing things like cleaning and laundry."),
    ("先生の説明が難しくて、私には全く理解できなかった。", "The teacher's explanation was so difficult that I couldn't understand it at all."),
    ("このレストランのカレーは辛すぎて、全部食べられません。", "The curry at this restaurant is so spicy that I can't eat all of it."),
    ("明日は早く起きなければならないので、もう寝ます。", "I have to wake up early tomorrow, so I'm going to sleep now."),
    ("彼は約束の時間に間に合うように、急いで駅に向かった。", "He hurried to the station so that he would be in time for the appointment."),
    ("どんなに大変でも、最後まで諦めずに頑張りたいです。", "No matter how tough it is, I want to do my best without giving up until the end."),
    ("新しいパソコンを買うなら、あの店が一番安いらしいよ。", "If you're buying a new computer, it seems that store is the cheapest."),
    ("子供の頃、よくこの公園で友達と遊んだものだ。", "When I was a child, I used to play a lot with my friends in this park."),
    ("この映画は子供向けにしては、内容が少し難しすぎる。", "For a movie aimed at children, the content is a bit too difficult."),
    ("会議中なので、携帯電話の電源は切っておいてください。", "Since we are in a meeting, please keep your mobile phone turned off."),
    ("私は甘いものが好きなので、毎日ケーキを食べずにはいられない。", "Because I love sweets, I can't help but eat cake every day."),
    ("この薬を飲めば、すぐに熱が下がるはずです。", "If you take this medicine, your fever should go down right away."),
    ("私の代わりに、会議に出席してもらえませんか。", "Could you attend the meeting in my place?"),
    ("山田さんは今日は休むと言っていたから、来ないだろう。", "Yamada said he was taking the day off today, so he probably won't come."),
    ("窓を開けたとたん、冷たい風が部屋に入ってきた。", "As soon as I opened the window, a cold wind came into the room."),
    ("あのホテルは景色が良い代わりに、値段が少し高い。", "That hotel has a good view, but in exchange, the price is a little high."),
    ("これ以上無理をすると、病気になりかねないから休んだ方がいい。", "If you push yourself any harder, you might get sick, so you should rest."),
    ("彼はとても忙しいらしく、最近あまり連絡がこない。", "He seems very busy and hasn't contacted me much recently."),
    ("新しいプロジェクトを成功させるために、みんなで協力しましょう。", "Let's all cooperate in order to make the new project a success."),
    ("この辞書は小さくて軽いから、持ち歩くのにとても便利だ。", "This dictionary is small and light, so it is very convenient for carrying around."),
    ("明日の天気は晴れだということなので、ピクニックに行ける。", "I heard tomorrow's weather will be sunny, so we can go for a picnic."),
    ("一生懸命勉強したおかげで、希望の大学に合格することができた。", "Thanks to studying hard, I was able to pass the university of my choice."),
    ("今朝は寝坊してしまったせいで、朝ごはんを食べる時間がなかった。", "Because I overslept this morning, I didn't have time to eat breakfast."),
    ("彼は本当に日本人かと思うくらい、上手に英語を話す。", "He speaks English so well that I wonder if he's really Japanese."),
    ("この料理は誰が食べても美味しいと言うに違いない。", "I'm sure anyone who eats this dish will say it's delicious."),
    ("急に雨が降り出したので、傘を買わざるを得なかった。", "It suddenly started raining, so I had no choice but to buy an umbrella."),
    ("彼は経験が浅いものの、仕事への情熱は誰にも負けない。", "Although he has little experience, his passion for work is second to none."),
    ("あの人はお金持ちだからといって、必ずしも幸せだとは限らない。", "Just because that person is rich doesn't necessarily mean they are happy."),
    ("いくら説明しても、彼女には私の気持ちが分かってもらえなかった。", "No matter how much I explained, she didn't understand my feelings."),
    ("駅前には大きなスーパーがあるから、買い物には困らない。", "There is a large supermarket in front of the station, so I don't have trouble shopping."),
    ("来週のテストに向けて、毎日図書館で勉強しているところだ。", "I am currently studying at the library every day for next week's test."),
    ("彼はスポーツマンらしく、いつも元気で爽やかだ。", "He is always energetic and refreshing, just like an athlete."),
    ("この街は夜になると急に静かになって、少し寂しいくらいだ。", "This town suddenly gets so quiet at night that it's almost a little lonely."),
    ("このパソコンの使い方が分からないので、教えてもらえませんか。", "I don't know how to use this computer, so could you teach me?"),
    ("こんなに高い時計、私にはとても買えそうにない。", "I don't think I could possibly buy such an expensive watch."),
    ("明日は大切な会議があるから、絶対に遅刻するわけにはいかない。", "Since there is an important meeting tomorrow, I absolutely cannot afford to be late."),
    ("彼女の料理は、プロのシェフが作ったかのように美味しい。", "Her cooking is so delicious it's as if a professional chef made it."),
    ("彼は何も知らないふりをしているが、本当はすべて知っているはずだ。", "He is pretending to know nothing, but he must actually know everything."),
    ("最近太ってきたから、毎朝ジョギングすることにしている。", "Since I've been gaining weight recently, I make it a rule to jog every morning."),
    ("どんな困難があっても、自分の夢に向かって進み続けたい。", "No matter what difficulties there are, I want to keep moving towards my dream."),
    ("この本は漢字ばかりで、外国人には少し読みにくいかもしれない。", "This book is full of kanji, so it might be a bit hard for foreigners to read."),
    ("友達に勧められた映画を見たが、期待していたほど面白くなかった。", "I watched the movie recommended by my friend, but it wasn't as interesting as I had expected.")
]
