sentences_2 = [
    ("あの人は英語だけでなく、フランス語も少し話せるそうだ。", "I hear that person can speak not only English but also a little French."),
    ("休みの日は、家で本を読んだり音楽を聴いたりして過ごすのが好きだ。", "On days off, I like to spend my time at home doing things like reading books and listening to music."),
    ("彼はいつも遅刻してくるから、今日も遅れるに違いない。", "He is always late, so he must be late today too."),
    ("新しいスマートフォンが欲しいけれど、高すぎて買えそうもない。", "I want a new smartphone, but it's so expensive I don't think I can buy it."),
    ("電車の中で寝過ごしてしまって、危うく終点まで行くところだった。", "I overslept on the train and was about to go all the way to the last stop."),
    ("来週の月曜日は祝日なので、学校はお休みということだ。", "Next Monday is a public holiday, so I heard there is no school."),
    ("彼女の部屋はいつもきれいに片付いていて、モデルルームのようだ。", "Her room is always neatly tidied up, like a model room."),
    ("このカレーは私には辛すぎるので、もう少し甘いのがいいです。", "This curry is too spicy for me, so I prefer something a little sweeter."),
    ("どんなに疲れていても、お風呂に入らずに寝るわけにはいかない。", "No matter how tired I am, I can't possibly go to sleep without taking a bath."),
    ("あのホテルは料金が高いわりに、サービスがあまり良くないらしい。", "I heard that hotel doesn't have very good service, considering its high price."),
    ("私が困っていると、いつも親切な友達が助けてくれる。", "Whenever I'm in trouble, a kind friend always helps me."),
    ("新しいレストランができたらしいから、今度一緒に行ってみよう。", "I heard a new restaurant opened, so let's go check it out together next time."),
    ("一生懸命練習したからには、絶対に優勝したいと思っている。", "Since I practiced so hard, I absolutely want to win the championship."),
    ("急に雨が降り出したせいで、せっかくのバーベキューが台無しになった。", "Because it suddenly started raining, our precious barbecue was ruined."),
    ("毎日少しずつでも勉強を続けることが大切だと言われている。", "It is said that continuing to study even a little bit every day is important."),
    ("彼は風邪を引いているのにもかかわらず、無理して仕事に来た。", "Even though he had a cold, he pushed himself and came to work."),
    ("このカメラは初心者でも簡単に綺麗な写真が撮れるようになっている。", "This camera is designed so that even beginners can easily take beautiful photos."),
    ("駅までの道が分からないので、誰かに教えてもらおうと思う。", "I don't know the way to the station, so I think I'll ask someone to tell me."),
    ("今日は疲れたから、夕ご飯は外食にしようかと思っているところだ。", "I'm tired today, so I'm thinking about eating out for dinner."),
    ("彼は嘘をついているに違いないと、私は最初から疑っていた。", "I suspected from the beginning that he must be lying."),
    ("私の代わりに荷物を受け取ってくれる人がいなくて困っている。", "I'm in trouble because there is no one to receive the package in my place."),
    ("この小説は感動的で、涙なしには最後まで読めなかった。", "This novel was so moving that I couldn't read it to the end without tears."),
    ("新しい服を買ったものの、着ていく場所がなくて少し残念だ。", "Although I bought new clothes, it's a bit disappointing that I have nowhere to wear them."),
    ("山田さんは日本人らしくない考え方をするので、話していて面白い。", "Yamada-san has an un-Japanese way of thinking, so it's interesting to talk to him."),
    ("もっと早く出発すればよかったと、今さら後悔しても仕方がない。", "It's no use regretting now that I should have left earlier."),
    ("いくら説明書を読んでも、この機械の使い方がさっぱり分からない。", "No matter how much I read the manual, I don't understand how to use this machine at all."),
    ("子供が道路に飛び出しそうになって、ひやっとしたよ。", "The child was about to jump out into the road, and it gave me a chill."),
    ("明日は早く起きるつもりだったのに、結局夜更かししてしまった。", "Even though I intended to wake up early tomorrow, I ended up staying up late after all."),
    ("彼はスポーツが得意なばかりか、成績もいつもトップクラスだ。", "Not only is he good at sports, but his grades are also always top class."),
    ("コーヒーを飲んだおかげで、ようやく目が覚めてきた気がする。", "Thanks to drinking coffee, I feel like I've finally woken up."),
    ("あの映画はつまらないらしいから、見に行かないほうがいいよ。", "I heard that movie is boring, so you'd better not go see it."),
    ("日本語のニュースが少しずつ聞き取れるようになってきて嬉しい。", "I'm glad that I'm becoming able to understand Japanese news a little by little."),
    ("この問題は難しすぎて、先生でさえ解けないかもしれない。", "This problem is so difficult that even the teacher might not be able to solve it."),
    ("来月京都へ行くことになったので、美味しいお店を調べている。", "It's been decided that I'm going to Kyoto next month, so I'm looking up delicious restaurants."),
    ("彼はとても疲れているようで、今にも倒れそうな顔をしている。", "He looks very tired and has a face like he's going to collapse at any moment."),
    ("雨が降ろうが降るまいが、明日のピクニックは決行するつもりだ。", "Whether it rains or not, we intend to go ahead with tomorrow's picnic."),
    ("こんなにたくさんのお土産、一人では持ちきれないよ。", "I can't possibly carry this many souvenirs by myself."),
    ("あの人は親切なふりをして、実は自分の利益しか考えていない。", "That person pretends to be kind, but actually only thinks about their own profit."),
    ("もっと勉強しておけばよかったと、試験の結果を見て後悔した。", "I regretted that I should have studied more after seeing the test results."),
    ("彼はまるで何もなかったかのように、いつも通り挨拶してきた。", "He greeted me as usual, exactly as if nothing had happened."),
    ("この店のラーメンは美味しいが、少し塩辛すぎるきらいがある。", "This shop's ramen is delicious, but it has a tendency to be a bit too salty."),
    ("早く家に帰って、温かいお風呂に入りたくてたまらない。", "I want to go home early and take a warm bath so badly."),
    ("新しいゲームを始めたら面白くて、やめられなくなってしまった。", "When I started a new game, it was so interesting that I couldn't stop."),
    ("山田さんは休むと言っていたから、今日はもう来ないはずだ。", "Yamada-san said he would take the day off, so he shouldn't be coming today."),
    ("私がもっとしっかりしていれば、こんな失敗は防げたのに。", "If I had been more reliable, I could have prevented such a failure."),
    ("彼は毎日遅くまで残業しているせいで、最近体調を崩しがちだ。", "Because he works overtime until late every day, he tends to get sick recently."),
    ("このパソコンは古いわりに、まだ十分早く動いてくれる。", "Considering this computer is old, it still runs fast enough."),
    ("明日の会議には、遅れてもいいから必ず出席するようにしてください。", "Please make sure to attend tomorrow's meeting, even if you are late."),
    ("彼は誰にでも優しいから、みんなから好かれているのも当然だ。", "Since he is kind to everyone, it's natural that he is liked by everyone."),
    ("もう少しで完成するところだったのに、パソコンがフリーズしてしまった。", "It was just about to be completed, but the computer froze.")
]
