const sent_topup_2 = [
    ["このホテルは景色も良くサービスも最高なのだが、交通の便が悪いのが少し残念だ。", "This hotel has good scenery and the service is also the best, but it's a bit disappointing that public transportation access is bad."],
    ["彼からのメールには要件だけが短く書かれており、冷たい印象を受けた。", "His email had only the main points written shortly, and I received a cold impression from it."],
    ["いくら若くて体力があるからといって、三日も徹夜するのは無茶というものだ。", "No matter how young you are and how much physical stamina you have, staying up all night for three days is what you'd call unreasonable."],
    ["あの店はいつも行列ができているけれど、並んでまで食べる価値があるかは疑問だ。", "That shop always has a line, but I doubt whether it's worth lining up to eat there."],
    ["彼は会議中ずっと黙っていたかと思うと、突然鋭い意見を言い出して周りを驚かせた。", "Just when I thought he had been silent the whole time during the meeting, he suddenly voiced a sharp opinion and surprised everyone around him."],
    ["新しい言語を習得するには、文法を覚えることと同じくらい実際に話す練習が不可欠だ。", "To acquire a new language, practice actually speaking is just as indispensable as memorizing grammar."],
    ["彼女の作ったケーキはプロ並みの仕上がりで、食べるのがもったいないくらいだった。", "The cake she made had a professional-level finish, to the point where it felt like a waste to eat it."],
    ["もしあの時違う道を選んでいたとしたら、今の私はどうなっていたのだろうか。", "Assuming I had chosen a different path at that time, I wonder what the me of today would have become."],
    ["彼は自分の非を認めるどころか、ますます開き直って文句を言い始めた。", "Far from admitting his own fault, he became increasingly defiant and started complaining."],
    ["あの映画の主人公は、どんな困難にも負けずに夢を追い続ける姿が魅力的だ。", "The protagonist of that movie has a charming figure that continues to chase their dream without giving in to any difficulties."],
    ["急な雨で濡れてしまった上に、電車も遅延して最悪な一日になってしまった。", "On top of getting wet from sudden rain, the train was also delayed, making it the worst day."],
    ["いくら注意しても直らないのだから、もう彼には何も言わないことにした。", "Since he won't fix it no matter how much I warn him, I decided to not say anything to him anymore."],
    ["このアプリは操作が簡単なだけでなく、デザインも洗練されていて使い心地が良い。", "This app is not only simple to operate, but its design is also refined, making it comfortable to use."],
    ["彼は何も知らないふりをしているが、実は計画の全てを裏で操っているに違いない。", "He is pretending to know nothing, but he must actually be manipulating the entire plan behind the scenes."],
    ["せっかくの休日なのに、朝からずっと家でゴロゴロしていて少しもったいない気がする。", "Even though it's a precious day off, I feel it's a bit of a waste to be lounging around at home all day since morning."],
    ["あの人はいつも人の悪口を言っているから、いずれ誰からも相手にされなくなるだろう。", "Because that person is always saying bad things about others, eventually they probably won't be dealt with by anyone."],
    ["彼はとても優秀なエンジニアである反面、チームでのコミュニケーションが少し苦手だ。", "While he is a very excellent engineer on one hand, he is a bit bad at communication within a team."],
    ["いくら説明書を読んでも分からないので、詳しい友達に使い方を聞くしかなかった。", "Since I couldn't understand no matter how much I read the manual, I had no choice but to ask a knowledgeable friend how to use it."],
    ["あのチームの結束力は固く、ちょっとやそっとの困難では決して揺らぐことはない。", "That team's solidarity is solid, and it will by no means be shaken by just a little bit of difficulty."],
    ["明日までにこの資料を完成させなければならないので、今夜は徹夜を覚悟している。", "Since I have to complete this document by tomorrow, I am prepared to stay up all night tonight."],
    ["彼女はいつも周りの人に気配りができて、本当に素晴らしい性格の持ち主だと思う。", "She can always be considerate of the people around her, and I think she is truly an owner of a wonderful personality."],
    ["このレストランは料理が出るのが遅いが、味は確かなので待つだけの価値はある。", "This restaurant is slow at serving food, but the taste is reliable, so it's worth the wait."],
    ["彼があんなに怒っている姿を見たのは初めてで、何があったのかとても気になる。", "It was the first time I saw him looking so angry, and I'm very curious about what happened."],
    ["いくらお金がたくさんあっても、健康でなければ本当の幸せとは言えないだろう。", "No matter how much money you have, if you are not healthy, it probably cannot be called true happiness."],
    ["あの映画の結末は賛否両論あるようだが、私個人としてはとても感動的な終わり方だったと思う。", "It seems the ending of that movie has both pros and cons, but personally, I think it was a very moving way to end."],
    ["彼は自分の意見を曲げようとしないので、これ以上話し合っても時間の無駄かもしれない。", "Because he won't try to bend his own opinion, discussing it any further might be a waste of time."],
    ["この町の治安は昔に比べるとだいぶ悪くなっており、夜の一人歩きは少し危険だ。", "The public safety in this town has gotten quite a bit worse compared to the past, and walking alone at night is a little dangerous."],
    ["彼女が作ってくれた手料理は、どんな高級レストランの料理よりも美味しく感じられた。", "The home-cooked meal she made for me felt more delicious than the food at any high-class restaurant."],
    ["もし宝くじで一億円当たったとしたら、仕事を辞めて世界中を旅行してみたいものだ。", "Assuming I won 100 million yen in the lottery, I would like to quit my job and travel all over the world."],
    ["彼とはずっと意見が合わずにケンカばかりしていたが、今では一番の親友になっている。", "I used to always disagree with him and fight all the time, but now he has become my best friend."]
];

module.exports = { sent_topup_2 };
