const sent_topup = [
    ["新しい企画について、会議でもっと具体的に話し合う必要がある。", "We need to discuss the new project more specifically in the meeting."],
    ["彼からの返事が遅いので、本当に手紙が届いたのか心配になってきた。", "His reply is slow, so I've become worried whether the letter really arrived."],
    ["せっかく映画館まで来たのに、チケットが売り切れていて見られなかった。", "Even though I came all the way to the movie theater, I couldn't watch it because tickets were sold out."],
    ["スマートフォンの画面を見ながら歩くのは、非常に危険なのでやめましょう。", "Walking while looking at a smartphone screen is extremely dangerous, so let's stop doing it."],
    ["いくら急いでいるからといって、赤信号を無視して道路を渡ってはいけない。", "No matter how much you are in a hurry, you must not ignore the red light and cross the road."],
    ["最近は忙しすぎて、ゆっくり休む時間さえ取れない状態が続いている。", "Recently I've been so busy that the situation of not even being able to take time to rest properly continues."],
    ["もし彼が約束を破るようなことがあれば、もう二度と信用しないつもりだ。", "If he were to do something like break his promise, I intend to never trust him again."],
    ["この仕事は、専門的な知識を持った人でなければ担当するのは難しいだろう。", "This job would probably be difficult to take charge of unless it's a person with specialized knowledge."],
    ["昨日から降り続いた雪のおかげで、町全体が真っ白で美しい景色になった。", "Thanks to the snow that continued falling since yesterday, the whole town became a pure white and beautiful scenery."],
    ["少し熱があるが、大事な会議があるので会社を休むわけにはいかない。", "I have a slight fever, but since there is an important meeting, I cannot possibly take the day off from work."],
    ["彼女のピアノの腕前は、プロの音楽家が驚くほど素晴らしいものだった。", "Her piano skills were something so wonderful that even professional musicians would be surprised."],
    ["この薬は食後に飲まないと胃を痛める恐れがあるので注意してください。", "Please be careful because if you don't take this medicine after meals, there is a risk of hurting your stomach."],
    ["彼は何も言わずに部屋を出て行ったが、きっと怒っているに違いない。", "He left the room without saying anything, but he must surely be angry."],
    ["インターネットを使えば、世界中のあらゆる情報を一瞬で手に入れることができる。", "If you use the internet, you can obtain all sorts of information from all over the world in an instant."],
    ["たとえ親に反対されたとしても、私はこの仕事を続ける決心をしている。", "Even if I am opposed by my parents, I am determined to continue this job."],
    ["新しいパソコンの設定が複雑すぎて、説明書を読んでもさっぱり分からない。", "The settings of the new computer are so complicated that even if I read the manual, I don't understand it at all."],
    ["彼はただ頭が良いだけでなく、困っている人を助ける優しさも持っている。", "Not only is he just smart, but he also has the kindness to help people in trouble."],
    ["子供の頃に夢見ていたことが、ついに現実のものとなって本当に嬉しい。", "What I dreamed of when I was a child has finally become a reality, and I am truly happy."],
    ["この料理は見た目が悪いわりに、食べてみると驚くほど美味しい味がする。", "Considering this dish looks bad, when you try eating it, it has a surprisingly delicious taste."],
    ["いくら健康に良いからといって、同じものばかり食べるのは良くない。", "No matter how good it is for your health, eating only the same thing all the time is not good."],
    ["明日テストがあるにもかかわらず、彼は全く勉強せずにゲームばかりしている。", "Despite having a test tomorrow, he isn't studying at all and is just playing games."],
    ["道に迷ってしまったら、近くの人に駅への行き方を尋ねた方が早い。", "If you get lost, it's faster to ask someone nearby for directions to the station."],
    ["彼女の努力が実を結び、ついに念願のレストランをオープンすることができた。", "Her efforts bore fruit, and she was finally able to open the restaurant of her heart's desire."],
    ["あの有名な歌手のコンサートチケットは、発売と同時に売り切れてしまったらしい。", "It seems the concert tickets for that famous singer sold out at the same time they went on sale."],
    ["最近少し太ってきたので、エレベーターを使わずに階段を上るようにしている。", "Since I've gained a little weight recently, I'm making a point to climb the stairs without using the elevator."],
    ["彼は風邪を引いているふりをしているが、本当は仕事に行きたくないだけだ。", "He is pretending to have a cold, but the truth is he just doesn't want to go to work."],
    ["このまま環境破壊が進めば、美しい自然が完全に失われかねない。", "If environmental destruction continues like this, beautiful nature might be completely lost."],
    ["友達とケンカをしてしまったが、どうやって謝ればいいのか分からない。", "I ended up having a fight with my friend, but I don't know how I should apologize."],
    ["彼の説明は分かりやすくて、まるで専門家が話しているかのようだった。", "His explanation was easy to understand, exactly as if an expert were talking."],
    ["明日から旅行に行くのだから、今夜のうちに荷物の準備をしておこう。", "Since I'm going on a trip starting tomorrow, I'll get my luggage prepared during tonight."],
    ["この町の治安はとても良くて、夜遅くに女性が一人で歩いても安全だ。", "The public safety in this town is very good, and it is safe even for a woman to walk alone late at night."],
    ["彼が遅刻してきたせいで、せっかく予定していた映画が見られなくなった。", "Because he came late, we couldn't watch the movie we had taken the trouble to plan for."],
    ["この古い建物は、あと数ヶ月で取り壊されることになっているそうだ。", "I hear this old building is scheduled to be torn down in a few more months."],
    ["彼女の意見はいつも鋭く、会議のたびに新しい視点を与えてくれる。", "Her opinions are always sharp and give us a new perspective every time there is a meeting."],
    ["急用ができたので、申し訳ありませんが今日の約束はキャンセルさせてください。", "An urgent matter came up, so I am very sorry, but please let me cancel today's appointment."],
    ["あのレストランは値段が高い割には、料理の味もサービスも大したことがない。", "Considering that restaurant's high prices, neither the taste of the food nor the service is anything special."],
    ["一生懸命探したものの、なくした指輪は結局どこからも見つからなかった。", "Although I searched as hard as I could, the lost ring was eventually found nowhere."],
    ["日本の夏は蒸し暑いので、エアコンなしで過ごすのはかなり厳しい。", "Summers in Japan are humid and hot, so spending them without an air conditioner is quite tough."],
    ["この小説は最後がとても感動的で、涙を流さずにはいられなかった。", "The end of this novel was so moving that I couldn't help but shed tears."],
    ["彼に何回も電話をかけたが、一向に電話に出る気配がない。", "I called him many times, but there is no sign at all that he is going to answer the phone."],
    ["週末は家でごろごろしているよりも、外に出てスポーツをする方が好きだ。", "Rather than lounging around at home on the weekend, I prefer going outside and playing sports."],
    ["あのチームは練習量が足りないから、明日の試合には勝てないだろう。", "That team lacks the amount of practice, so they probably won't be able to win tomorrow's match."],
    ["新しい家を建てる場所を探しているが、なかなか条件に合う土地が見つからない。", "I am looking for a place to build a new house, but I can't quite find land that meets my conditions."],
    ["彼の仕事のスピードは誰よりも速く、周りの人たちも驚くくらいだ。", "His working speed is faster than anyone else, to the extent that the people around him are also surprised."],
    ["明日は早く起きなければならないから、今夜はもうテレビを消して寝よう。", "Since I have to wake up early tomorrow, I'll turn off the TV now and go to sleep tonight."],
    ["あの映画の結末は、私が予想していたものとは全く違って驚いた。", "The ending of that movie was completely different from what I had expected, and I was surprised."],
    ["こんなに難しい問題、私に解けるわけがないので先生に聞いてみます。", "There is no way I can solve such a difficult problem, so I'll try asking the teacher."],
    ["彼女はとても優しくて、困っている人がいたら必ず声をかけて助けてあげる。", "She is very kind, and if there is someone in trouble, she will without fail call out and help them."],
    ["彼があの大学に合格できたのは、毎日寝る間も惜しんで勉強したおかげだ。", "The reason he was able to pass that university's entrance exam is thanks to studying every day, sparing even the time to sleep."],
    ["急に強い風が吹いてきたので、傘をさすのを諦めて走って帰った。", "Because a strong wind suddenly started blowing, I gave up holding my umbrella and ran home."],
    ["私が一生懸命作ったケーキを、美味しいと言って全部食べてくれて嬉しかった。", "I was happy that you said the cake I made with all my might was delicious and ate all of it."],
    ["この電車は特急なので、途中の小さな駅には停車しないことになっている。", "Since this train is a limited express, it is scheduled not to stop at small stations along the way."],
    ["少し休んだら体調が良くなってきたので、もう少し仕事を続けようと思う。", "Since my physical condition got better after resting a little, I think I'll continue working a little more."],
    ["外国語を上達させるためには、毎日少しずつでも声に出して読むことが大切だ。", "In order to improve at a foreign language, it is important to read out loud even a little bit every day."],
    ["彼は自分の失敗を他人のせいにばかりしていて、全く反省している様子がない。", "He only ever blames his own failures on other people and shows no sign of reflecting on it at all."],
    ["もし本当に宝くじが当たったら、世界中を旅行して回りたいものだ。", "If I were to really win the lottery, I would love to travel all around the world."],
    ["あの人はいつも文句ばかり言っているので、周りの人から嫌われているらしい。", "I hear that person is disliked by people around him because he is always doing nothing but complaining."],
    ["いくら好きだからといって、毎日ラーメンばかり食べていたら体を壊しますよ。", "No matter how much you like it, if you eat nothing but ramen every day, you will ruin your health."],
    ["彼とは何年も会っていないが、昔のように気軽に話せる気がする。", "I haven't met with him for years, but I feel like we can talk casually just like the old days."],
    ["この問題については、皆でもう少し時間をかけて話し合うべきだと思います。", "Regarding this issue, I think everyone should take a little more time and discuss it."],
    ["子供の頃はあんなに苦手だったピーマンが、大人になったら好きになった。", "Green peppers, which I disliked so much when I was a child, became something I like once I became an adult."],
    ["新しいパソコンの使い方がどうしても分からないので、友達に教えてもらうことにした。", "Since I absolutely can't figure out how to use the new computer, I decided to have my friend teach me."],
    ["明日は朝早く出発するので、今日のうちに荷物の準備を済ませておきたい。", "Because I will depart early tomorrow morning, I want to finish preparing my luggage today."],
    ["あの店はいつも行列ができているから、きっと美味しい料理を出すに違いない。", "Since that shop always has a line, they must surely serve delicious food."],
    ["彼女は本当に日本のアニメに詳しくて、どんな質問にもすぐに答えられる。", "She is truly knowledgeable about Japanese anime and can answer any question immediately."],
    ["この辺りは街灯が少なくて暗いので、夜歩くときは十分に注意してください。", "This area has few streetlights and is dark, so please be fully careful when walking at night."],
    ["一生懸命勉強したからには、なんとしても今回のテストで満点を取りたい。", "Since I studied as hard as I could, I want to get a perfect score on this test no matter what."],
    ["彼は風邪を引いているのにもかかわらず、無理して残業を続けているようだ。", "It seems he continues to push himself and work overtime despite having a cold."],
    ["明日の会議には、社長をはじめとする会社の重要なメンバー全員が出席する。", "All the important members of the company, starting with the president, will attend tomorrow's meeting."],
    ["こんなに美味しいお寿司を食べたのは、日本に来てから初めてのことだ。", "Eating such delicious sushi is a first for me since coming to Japan."],
    ["彼の説明はまるで専門家が話しているかのように分かりやすく、説得力があった。", "His explanation was easy to understand and persuasive, exactly as if an expert were talking."],
    ["急に大雨が降ってきたせいで、せっかくのバーベキューが台無しになってしまった。", "Because heavy rain suddenly started falling, our precious barbecue ended up completely ruined."],
    ["あの俳優は演技が上手いだけでなく、歌も素晴らしいのでファンが多い。", "That actor is not only good at acting but also wonderful at singing, so he has many fans."],
    ["この本は専門的な用語が多くて、普通の人が理解するには少し難しすぎる。", "This book has many specialized terms, and it's a bit too difficult for an ordinary person to understand."],
    ["私が何度注意しても、彼は全く態度を改めようとしないので困っている。", "No matter how many times I warn him, he doesn't try to improve his attitude at all, which is troubling."],
    ["来週は重要な試験があるから、友達からの遊びの誘いも断らざるを得ない。", "Since there is an important exam next week, I have no choice but to refuse even my friends' invitations to play."],
    ["彼はいつも約束の時間を守らないので、もう誰も彼を信用しなくなってしまった。", "Because he never keeps the promised time, nobody trusts him anymore."],
    ["この店は値段が安いわりに、量がとても多くて学生にはありがたい存在だ。", "Considering this shop's low prices, the portions are very large, making it a thankful existence for students."],
    ["少し休んだら痛みが治まったので、なんとか最後まで歩き切ることができた。", "Since the pain subsided after resting a little, I managed to walk all the way to the end somehow."],
    ["彼女はとても頭が良い反面、少し人の気持ちを理解するのが苦手なところがある。", "While she is very smart on one hand, she has a side that is a bit bad at understanding people's feelings."],
    ["子供の頃に住んでいた町を久しぶりに訪れてみたが、すっかり変わっていて驚いた。", "I tried visiting the town I lived in as a child for the first time in a while, but I was surprised that it had completely changed."],
    ["この薬は効果が強い代わりに、眠くなるなどの副作用が出ることもあるそうです。", "I hear this medicine has strong effects, but in exchange, side effects such as getting sleepy may also appear."],
    ["彼があの難しい試験に一回で合格できたのは、日々の努力のたまものだ。", "The fact that he was able to pass that difficult exam on the first try is the fruit of his daily efforts."],
    ["もし明日雨が降ったとしたら、ピクニックは中止にして家で映画を見よう。", "Assuming it rains tomorrow, let's cancel the picnic and watch a movie at home."],
    ["いくら彼が才能を持っているとはいえ、全く練習しなければ試合に勝てないだろう。", "No matter how much talent he has, if he doesn't practice at all he probably won't be able to win the match."],
    ["このプロジェクトは、皆が協力してくれなければ決して成功することはないだろう。", "This project will probably never succeed unless everyone cooperates."],
    ["昨日見た映画のラストシーンがとても衝撃的で、今でも頭から離れない。", "The last scene of the movie I watched yesterday was so shocking that it still won't leave my head."],
    ["彼は何か言いたげな顔をしていたが、結局何も言わずに帰ってしまった。", "He had a look like he wanted to say something, but he ended up going home without saying anything."],
    ["この辞書は小さくて軽いから、かばんに入れて持ち歩くのにとても便利だ。", "Since this dictionary is small and light, it is very convenient for putting in a bag and carrying around."],
    ["彼がわざと嘘をついたとは考えにくいので、何か理由があるに違いない。", "It's hard to think that he told a lie on purpose, so there must surely be some reason."],
    ["今日は朝から頭が痛くて、薬を飲んでもなかなか治らなくて困っている。", "My head has been hurting since morning today, and even though I took medicine it won't easily cure, which is troubling."],
    ["あの店はいつも混雑しているので、予約をしないで行くのはやめた方がいい。", "That shop is always crowded, so you'd better stop going without making a reservation."],
    ["日本語の勉強を続ければ続けるほど、言葉の奥深さに気づかされる気がする。", "The more I continue studying Japanese, the more I feel I am made to realize the depth of the language."],
    ["彼女は私の話を全く聞いていないかのごとく、自分のことばかり話し続けた。", "She continued to talk only about herself, exactly as if she hadn't been listening to my story at all."],
    ["このマンションは駅から近いという利点があるものの、家賃が高すぎるのが欠点だ。", "Although this apartment has the advantage of being close to the station, the drawback is that the rent is too high."],
    ["彼があんなに急いで部屋を出て行ったのには、何か深い訳があるのだろう。", "There must be some deep reason for why he left the room in such a hurry."],
    ["いくら体に良いからといって、サプリメントばかりに頼るのは危険だと思う。", "No matter how good it is for the body, I think relying solely on supplements is dangerous."],
    ["彼は本当に反省しているのだろうか、全く謝る気配が見られないのだけれど。", "Is he truly reflecting on it, I wonder? I can't see any sign of him apologizing at all, though."],
    ["この料理の味付けは少し甘すぎるきらいがあるので、もう少し塩を足した方がいい。", "The seasoning of this dish tends to be a bit too sweet, so it's better to add a little more salt."],
    ["新しい環境に慣れるまでは誰でも不安なものだから、あまり心配しなくても大丈夫だ。", "It's normal for anyone to be anxious until they get used to a new environment, so it's okay not to worry too much."],
    ["明日のハイキングは、山の天気が変わりやすいので必ず雨具を持ってくるように。", "For tomorrow's hiking, the mountain weather changes easily, so make sure to bring rain gear without fail."],
    ["彼がそんな大きな間違いをするなんて、彼らしくない出来事だとみんなが驚いた。", "Everyone was surprised that he made such a big mistake, saying it was an incident unlike him."],
    ["この車は古いわりには燃費が良くて、長距離のドライブにも十分使えるレベルだ。", "Considering this car is old, it has good fuel efficiency and is at a level where it can be fully used for long-distance driving."],
    ["彼とはケンカばかりしているが、なんだかんだ言って一番の親友であることに変わりはない。", "I'm always fighting with him, but at the end of the day, it doesn't change the fact that he's my best friend."],
    ["いくら説明書を読んでも機械の使い方が分からないので、ついにメーカーに問い合わせた。", "No matter how much I read the manual, I didn't understand how to use the machine, so I finally inquired with the manufacturer."],
    ["彼女はいつも笑顔で挨拶してくれるので、朝からとても気持ちよく仕事が始められる。", "Because she always greets me with a smile, I can start work feeling very pleasant from the morning."],
    ["このレストランは雰囲気が良くて料理も美味しいから、デートには最適な場所だと思う。", "Because this restaurant has a good atmosphere and the food is also delicious, I think it's the optimal place for a date."],
    ["彼がそんなひどい嘘をつくような人だとは、実際に話を聞くまで信じられなかった。", "Until I actually heard the story, I couldn't believe that he was the kind of person to tell such a terrible lie."],
    ["明日は朝早く起きなければならないから、夜更かしせずに早く寝ようと心に決めた。", "Since I have to wake up early tomorrow morning, I resolved in my heart to go to bed early without staying up late."],
    ["いくら値段が安くても、デザインが気に入らなければその服を買うつもりは全くない。", "No matter how cheap the price is, if I don't like the design, I have no intention of buying those clothes at all."],
    ["この本は日本の歴史について非常に詳しく書かれており、専門家でも読み応えがある。", "This book is written in extreme detail about Japanese history, and even experts find it worth reading."],
    ["彼は自分が悪いと分かっているくせに、絶対に謝ろうとしないから本当に困ったものだ。", "Even though he knows he's in the wrong, he absolutely won't try to apologize, so he's truly a troublesome person."],
    ["急な用事が入ってしまったせいで、楽しみにしていた週末の旅行に行けなくなってしまった。", "Because an urgent errand came up, I ended up unable to go on the weekend trip I was looking forward to."],
    ["あの人はいつも人の悪口ばかり言っているので、周りから信頼されていないのも無理はない。", "That person is always saying nothing but bad things about others, so it's no wonder they aren't trusted by those around them."],
    ["もしタイムマシンがあったとしたら、自分が子供の頃に戻って当時の自分に会ってみたい。", "Assuming there was a time machine, I would like to return to when I was a child and meet my past self."],
    ["彼は本当に風邪を引いているのだろうか、昨日元気に遊んでいる姿を見たのだけれど。", "I wonder if he really has a cold; I saw him playing energetically yesterday, though."],
    ["このソフトウェアは便利である反面、使いこなすまでにかなり時間がかかるのが少し面倒だ。", "While this software is convenient on one hand, it is a bit troublesome that it takes quite a bit of time to master."],
    ["いくら失敗したからといって、そこで諦めてしまったら今までの努力がすべて無駄になる。", "No matter how much you failed, if you end up giving up there, all your efforts up to now will become a waste."],
    ["彼があの難しい仕事を一人でやり遂げたなんて、本当に信じられないくらい素晴らしいことだ。", "The fact that he accomplished that difficult job all by himself is something wonderful to the point of being truly unbelievable."],
    ["明日の試合は絶対に勝たなければならないから、最後まで気を抜かずに全力で戦おう。", "Because we absolutely must win tomorrow's match, let's fight with all our power without losing focus until the end."]
];

module.exports = { sent_topup };
