const vocab_topup = [
    ["迷惑", "annoyance, nuisance", "夜遅くに大声で話すのは近所の迷惑になります。", "Talking loudly late at night is a nuisance to the neighbors."],
    ["遠慮", "hesitation, restraint", "何も遠慮しないで、好きなものを注文してください。", "Please don't hesitate and order whatever you like."],
    ["感謝", "gratitude, appreciation", "いつも助けてくれる同僚に深く感謝している。", "I am deeply grateful to my colleagues who always help me."],
    ["謝る", "to apologize", "自分が間違っていたことに気づき、すぐに彼に謝った。", "I realized I was wrong and immediately apologized to him."],
    ["譲る", "to yield, to hand over", "満員のバスの中で、お年寄りに席を譲った。", "I gave up my seat to an elderly person on the crowded bus."],
    ["確かめる", "to confirm, to verify", "提出する前に、もう一度書類の数字を確かめてください。", "Please verify the numbers on the document once more before submitting."],
    ["偶然", "by chance, unexpectedly", "駅前で偶然、昔のクラスメイトに会って驚いた。", "I was surprised to run into an old classmate by chance in front of the station."],
    ["突然", "suddenly", "突然の強い雨で、服がすっかり濡れてしまった。", "My clothes got completely wet due to the sudden heavy rain."],
    ["不安", "anxiety, uneasiness", "新しい職場でうまくやっていけるかどうか不安だ。", "I am anxious about whether I can do well at my new workplace."],
    ["期待", "expectation, hope", "ファンの期待に応えるために、チームは全力を尽くした。", "The team did their absolute best to meet the fans' expectations."],
    ["失望", "disappointment", "彼が約束を破ったことに、ただ失望するしかなかった。", "I could do nothing but be disappointed that he broke his promise."],
    ["自信", "confidence", "何回も練習したので、明日のスピーチには自信がある。", "I have practiced many times, so I have confidence in tomorrow's speech."],
    ["諦める", "to give up", "どんなに難しくても、最後まで諦めずに挑戦したい。", "No matter how difficult it is, I want to try without giving up until the end."],
    ["我慢", "endurance, patience", "足が痛かったが、家に着くまで必死に我慢した。", "My legs hurt, but I desperately endured it until I got home."],
    ["苦労", "hardship, trouble", "若い頃に苦労した経験が、今の仕事に生きている。", "The hardships I experienced in my youth are useful in my current job."],
    ["影響", "influence, effect", "彼の言葉は、私のその後の人生に大きな影響を与えた。", "His words had a great influence on the rest of my life."],
    ["効果", "effect, effectiveness", "この薬を飲んだら、すぐに効果が表れて熱が下がった。", "When I took this medicine, it took effect immediately and my fever went down."],
    ["流行", "trend, fashion", "若者の間では、古着を取り入れたファッションが流行している。", "Among young people, fashion incorporating secondhand clothing is trending."],
    ["噂", "rumor", "その俳優が結婚するという噂は、あっという間に広まった。", "The rumor that the actor was getting married spread in the blink of an eye."],
    ["秘密", "secret", "この話は絶対に秘密にしておいてほしい。", "I want you to absolutely keep this conversation a secret."],
    ["冗談", "joke", "彼の冗談のおかげで、会議の緊張した空気が和らいだ。", "Thanks to his joke, the tense atmosphere of the meeting eased."],
    ["深刻", "serious, severe", "地球温暖化は、私たちが直面している深刻な問題だ。", "Global warming is a serious problem we are facing."],
    ["複雑", "complicated", "機械の構造が複雑すぎて、修理するのに時間がかかった。", "The structure of the machine was so complicated that it took a long time to repair."],
    ["解決", "solution, resolution", "両者の話し合いにより、トラブルは無事に解決した。", "Through discussion between both parties, the trouble was successfully resolved."],
    ["相談", "consultation", "進路について悩んでいるので、先生に相談してみるつもりだ。", "I am worried about my future path, so I intend to consult my teacher."],
    ["賛成", "approval, agreement", "新しい働き方の提案に対して、多くの社員が賛成した。", "Many employees agreed with the proposal for a new way of working."],
    ["反対", "opposition", "住民の強い反対により、その建物の建設は中止された。", "Due to strong opposition from the residents, the construction of the building was canceled."],
    ["提案", "proposal, suggestion", "コストを削減するための具体的なアイデアを提案した。", "I proposed a concrete idea for reducing costs."],
    ["契約", "contract", "アパートの契約を更新するために、不動産屋へ行った。", "I went to the real estate agency to renew my apartment contract."],
    ["面接", "interview", "明日の就職面接のために、スーツをクリーニングに出した。", "I took my suit to the dry cleaners for tomorrow's job interview."],
    ["採用", "recruitment, employment", "厳しい審査の結果、彼が新しいデザイナーとして採用された。", "As a result of strict screening, he was hired as the new designer."],
    ["辞める", "to quit, to resign", "自分の会社を立ち上げるために、10年働いた会社を辞めた。", "I quit the company I had worked at for 10 years to start my own business."],
    ["通勤", "commuting", "毎朝、満員電車で1時間かけて通勤するのは疲れる。", "It's tiring to commute for an hour every morning on a crowded train."],
    ["出張", "business trip", "来週は重要な会議があるため、大阪へ出張することになった。", "I will be going on a business trip to Osaka next week for an important meeting."],
    ["報告", "report", "プロジェクトの進み具合について、上司に報告書を提出した。", "I submitted a report to my boss regarding the progress of the project."],
    ["連絡", "contact, communication", "急な予定の変更があれば、すぐに携帯電話に連絡してください。", "If there is a sudden change in schedule, please contact my mobile phone immediately."],
    ["確認", "confirmation", "飛行機の出発時間を間違えないように、チケットを確認した。", "I checked my ticket so as not to mistake the airplane's departure time."],
    ["締め切り", "deadline", "レポートの締め切りは明日の午後5時なので、急いで書いている。", "The deadline for the report is 5 PM tomorrow, so I am writing it in a hurry."],
    ["延期", "postponement", "悪天候のため、野外イベントは来週に延期されました。", "Due to bad weather, the outdoor event was postponed to next week."],
    ["調整", "adjustment, coordination", "全員が参加できるように、会議のスケジュールを調整している。", "I am coordinating the meeting schedule so that everyone can participate."],
    ["変更", "change, alteration", "予約の人数に変更があった場合は、前日までにお知らせください。", "If there is a change in the number of people reserved, please let us know by the day before."],
    ["失敗", "failure", "何度か失敗を繰り返したが、ついに実験は成功した。", "I repeated failures a few times, but the experiment finally succeeded."],
    ["成功", "success", "このビジネスが成功するかどうかは、私たちの努力にかかっている。", "Whether this business succeeds or not depends on our efforts."],
    ["努力", "effort", "彼は毎日努力を続け、プロのサッカー選手になる夢を叶えた。", "He continued to make an effort every day and realized his dream of becoming a professional soccer player."],
    ["責任", "responsibility", "リーダーとして、チームの失敗に対する責任を果たすつもりだ。", "As a leader, I intend to take responsibility for the team's failure."],
    ["規則", "rule, regulations", "寮の規則を守らない学生には、厳しい注意が与えられる。", "Strict warnings are given to students who do not follow the dormitory rules."],
    ["法律", "law", "弁護士になるために、大学で法律を専門に勉強している。", "To become a lawyer, I am specializing in studying law at the university."],
    ["違反", "violation", "スピード違反で警察に止められ、罰金を払うことになった。", "I was stopped by the police for speeding and had to pay a fine."],
    ["事故", "accident", "高速道路で大きな事故があり、車が全く動かなくなった。", "There was a major accident on the highway, and the cars stopped moving entirely."],
    ["混雑", "congestion, crowding", "お正月の時期は、空港が非常に混雑するので注意が必要だ。", "You need to be careful during the New Year's period as the airport gets extremely crowded."],
    ["故障", "breakdown, failure", "エアコンが故障してしまい、部屋の中がとても暑い。", "The air conditioner has broken down, and it's very hot inside the room."],
    ["修理", "repair", "壊れた靴を修理に出したら、新品のように綺麗になって戻ってきた。", "When I sent my broken shoes in for repair, they came back looking as clean as new."],
    ["点検", "inspection", "安全のために、エレベーターの定期的な点検が行われている。", "For safety, regular inspections of the elevators are being carried out."],
    ["保険", "insurance", "万が一の病気やケガに備えて、医療保険に入っておくべきだ。", "You should get medical insurance in case of an unexpected illness or injury."],
    ["税金", "tax", "毎年、決められた期限までに正しく税金を納めなければならない。", "Every year, you must properly pay your taxes by the set deadline."],
    ["節約", "saving (money), economy", "将来のために、無駄な出費を減らして少しでも節約している。", "For the future, I am reducing wasteful spending and saving even a little."],
    ["無駄", "waste", "誰もいない部屋の電気をつけておくのは、電気代の無駄だ。", "Leaving the lights on in an empty room is a waste of electricity bills."],
    ["費用", "cost, expense", "海外留学には、授業料や生活費など多くの費用がかかる。", "Studying abroad requires a lot of expenses such as tuition and living costs."],
    ["価格", "price", "最近、スーパーで売られている野菜の価格が急に上がった。", "Recently, the price of vegetables sold at the supermarket has suddenly risen."],
    ["価値", "value", "この古い時計は、見た目はボロボロだが歴史的な価値がある。", "This old watch looks worn out but has historical value."],
    ["無料", "free of charge", "このアプリは無料でダウンロードできるが、一部の機能は有料だ。", "This app can be downloaded for free, but some features require payment."],
    ["割引", "discount", "学生証を見せると、映画館のチケットが20％割引になる。", "If you show your student ID, movie theater tickets get a 20% discount."],
    ["現金", "cash", "この店はクレジットカードが使えず、現金での支払いのみだ。", "This store does not accept credit cards and only takes cash payments."],
    ["貯金", "savings", "新しい車を買うために、毎月給料の一部を貯金している。", "I am saving a portion of my salary every month to buy a new car."],
    ["給料", "salary", "給料をもらったら、ずっと欲しかったカバンを買うつもりだ。", "Once I get my salary, I intend to buy the bag I've always wanted."],
    ["物価", "cost of living, prices", "都会は便利で楽しい場所だが、地方に比べて物価が高い。", "The city is a convenient and fun place, but the cost of living is higher compared to rural areas."],
    ["景気", "economic conditions", "国の経済対策のおかげで、少しずつ景気が回復してきた。", "Thanks to the country's economic measures, the economy has gradually recovered."],
    ["輸出", "export", "この国は、自動車や電子部品を世界中に輸出している。", "This country exports automobiles and electronic parts all over the world."],
    ["輸入", "import", "日本は食料の多くを海外からの輸入に頼っている。", "Japan relies on imports from overseas for much of its food."],
    ["農業", "agriculture", "私の祖父は田舎でずっと農業を続けていて、美味しい野菜を作っている。", "My grandfather has been continuing agriculture in the countryside and grows delicious vegetables."],
    ["工業", "manufacturing industry", "この地域は昔から工業が盛んで、多くの工場が建ち並んでいる。", "This region has prospered in manufacturing since old times, and many factories are lined up."],
    ["商業", "commerce", "駅前を中心に商業施設が集まり、いつも人で賑わっている。", "Commercial facilities are gathered around the station, and it is always crowded with people."],
    ["産業", "industry", "観光は、この町の経済を支える最も重要な産業の一つだ。", "Tourism is one of the most important industries supporting this town's economy."],
    ["観光", "sightseeing, tourism", "週末に京都へ行き、歴史的なお寺や神社を観光して回った。", "I went to Kyoto on the weekend and went sightseeing around historical temples and shrines."],
    ["滞在", "stay", "パリでの一週間の滞在中に、様々な美術館を訪れた。", "During my one-week stay in Paris, I visited various art museums."],
    ["予約", "reservation", "人気のレストランなので、事前に予約しておかないと入れない。", "Because it's a popular restaurant, you can't get in unless you make a reservation in advance."],
    ["案内", "guidance, information", "ボランティアの学生が、外国人観光客に町を案内していた。", "Student volunteers were showing foreign tourists around the town."],
    ["手続き", "procedure", "市役所で引っ越しの手続きをするのに、かなり時間がかかった。", "It took quite a bit of time to do the moving procedures at the city hall."],
    ["宅配便", "home delivery service", "親から送られてきた宅配便の中に、地元のお菓子が入っていた。", "There were local sweets in the home delivery package sent from my parents."],
    ["忘れ物", "lost property, something forgotten", "電車の中に傘を忘れたので、駅の忘れ物センターに問い合わせた。", "I left my umbrella on the train, so I inquired at the station's lost property center."],
    ["迷子", "lost child", "デパートで迷子になって泣いている子供を、サービスカウンターに連れて行った。", "I took a crying child who got lost in the department store to the service counter."],
    ["泥棒", "thief", "昨夜、留守の間に泥棒に入られ、現金と時計が盗まれた。", "Last night, while I was away, a thief broke in and my cash and watch were stolen."],
    ["被害", "damage, harm", "台風による農作物の被害は、想像以上に大きかった。", "The damage to agricultural crops caused by the typhoon was greater than imagined."],
    ["消防署", "fire station", "火事の知らせを受けると、消防署からすぐに消防車が出動した。", "Upon receiving the fire alarm, fire engines were immediately dispatched from the fire station."],
    ["看病", "nursing (a patient)", "風邪で寝込んでいる子供を、夜通し看病してすっかり疲れた。", "I am completely exhausted from nursing my child, who is in bed with a cold, all through the night."],
    ["薬局", "pharmacy", "病院でもらった処方箋を持って、近くの薬局へ薬をもらいに行った。", "I took the prescription I got at the hospital and went to a nearby pharmacy to get my medicine."],
    ["症状", "symptoms", "熱は下がったが、咳や喉の痛みといった症状がまだ続いている。", "My fever has gone down, but symptoms such as a cough and a sore throat are still continuing."],
    ["診察", "medical examination", "具合が悪いなら、無理をしないで早めに医者の診察を受けた方がいい。", "If you are not feeling well, you shouldn't push yourself and should get a doctor's medical examination early."],
    ["手術", "surgery, operation", "足のケガを完全に治すためには、簡単な手術が必要だと言われた。", "I was told that simple surgery is necessary to completely cure the injury to my leg."],
    ["注射", "injection", "インフルエンザを防ぐために、毎年冬の初めに予防注射を受けている。", "To prevent the flu, I get a preventive injection at the beginning of winter every year."],
    ["治療", "treatment", "虫歯の治療は痛いイメージがあったが、最近の技術は進歩している。", "I had an image that cavity treatment is painful, but recent technology has advanced."],
    ["回復", "recovery", "ゆっくり休んだおかげで、体力がすっかり回復して元気になった。", "Thanks to resting well, my physical strength has fully recovered and I feel energetic."],
    ["健康", "health", "健康を維持するために、バランスの取れた食事と適度な運動を心がけている。", "To maintain my health, I keep in mind to have a balanced diet and moderate exercise."],
    ["栄養", "nutrition", "野菜が不足しがちなので、サプリメントで栄養を補っている。", "I tend to lack vegetables, so I supplement my nutrition with supplements."],
    ["睡眠", "sleep", "質の良い睡眠をとることは、ストレスを減らすために非常に重要だ。", "Getting good quality sleep is extremely important for reducing stress."],
    ["疲労", "fatigue", "長時間の運転で目が疲労していたため、サービスエリアで少し休んだ。", "My eyes were experiencing fatigue from driving for a long time, so I rested a little at a service area."],
    ["運動", "exercise", "医者に運動不足を指摘されたので、毎朝ジョギングを始めることにした。", "The doctor pointed out my lack of exercise, so I decided to start jogging every morning."],
    ["予防", "prevention", "病気の予防には、手洗いとうがいを習慣にすることが一番効果的だ。", "For disease prevention, making handwashing and gargling a habit is the most effective."],
    ["具合", "condition (health)", "朝からお腹の具合が悪くて、今日の会議には集中できそうにない。", "The condition of my stomach has been bad since morning, and I don't think I can concentrate on today's meeting."]
];

module.exports = { vocab_topup };
